// The wire constants `crates/fathom-wasm/src/protocol.rs` and
// `crates/fathom-wasm/src/lib.rs` define, hand-copied because nothing
// generates this TypeScript file yet (ADR-0052 §1: "Face and error codes are
// generated from Rust, never typed twice").
//
// `client/src/engine/protocol.generated.json` now exists — generated by
// `cargo test -p fathom-wasm --test protocol_generated -- --ignored
// --nocapture` — and `protocol.constants.generated.test.ts` checks this
// file's numbers against it on every run, not trusted forever: a mismatch
// fails loudly there, not here, because a hand-copied table is exactly the
// kind of thing that drifts quietly. Keep the two in step by hand until this
// file itself is generated; a `grep` against `protocol.rs`/`lib.rs` is the
// re-check either way.

/** `lib.rs`'s opcode table (41 §3.7): stable forever, a new call is a new
 * opcode. 28–30 are ADR-0052 §4's three doors, implemented on the Rust side. */
export const OPCODES = {
  OP_INIT: 1,
  OP_QUERY: 4,
  OP_ESTATE_DEMO: 11,
  OP_INV_ROWS: 12,
  OP_ELEMENT: 13,
  OP_EQUIPMENT: 14,
  OP_PASTE: 15,
  OP_EQUIP_ADD: 16,
  OP_FIELD_SET: 17,
  OP_ELEMENT_REMOVE: 18,
  OP_DIAGRAM: 19,
  OP_DICT: 20,
  OP_PLACE: 21,
  OP_RACK_PLACE: 22,
  OP_RACK_ELEVATION: 23,
  OP_LINK: 24,
  OP_FINDINGS: 25,
  OP_INSIDE: 26,
  OP_CABLE: 27,
  /** ADR-0052 §4, door one: load the plain face into the module. */
  OP_LOAD_PLAIN: 28,
  /** ADR-0052 §4, door two: export the plain face back out. */
  OP_EXPORT_PLAIN: 29,
  /** ADR-0052 §4, door three: paste under a placed device. */
  OP_PASTE_INTO: 30,
} as const;

/** `protocol.rs`'s face role bytes — one `KIND_FACE_ROW` (5) record kind,
 * many roles, per that file's own note on why (`FACE_PASTE`'s doc comment). */
export const FACES = {
  FACE_HEADER: 0,
  FACE_INV: 1,
  FACE_FIELD: 2,
  FACE_PORT: 3,
  FACE_IFACE: 4,
  FACE_PASTE: 5,
  FACE_RESIDUE: 6,
  FACE_UNRESOLVED: 7,
  FACE_CAPTURE: 8,
  FACE_BOX: 9,
  FACE_LINE: 10,
  FACE_CANVAS: 11,
  FACE_RACK: 12,
  FACE_RACK_SLOT: 13,
  FACE_RACK_CLASH: 14,
  FACE_SHAPE: 15,
  FACE_GAP_HEAD: 16,
  FACE_GAP: 17,
  FACE_GAP_ITEM: 18,
  FACE_GAP_EMPTY: 19,
  FACE_INSIDE: 20,
  FACE_IN_IFACE: 21,
  FACE_IN_UNIT: 22,
  FACE_IN_ZONE: 23,
  FACE_IN_SET: 24,
  FACE_IN_POLICY: 25,
  FACE_IN_ROUTE: 26,
  FACE_IN_PROTO: 27,
  FACE_IN_TUNNEL: 28,
  FACE_INV_KEY: 29,
  /** ADR-0052 §2: one row per ledger line, the paste's gutter mark. */
  FACE_PASTE_LINE: 30,
  /** ADR-0052 §2: one row per value the gate destroyed. */
  FACE_DROP: 31,
} as const;

/** `protocol.rs`'s `ERR_*` codes carried on a `KIND_ERROR` (0) reply. */
export const ERRORS = {
  ERR_UNKNOWN_OP: 1,
  ERR_NOT_INITIALISED: 2,
  ERR_CORPUS_LOAD: 3,
  ERR_BAD_FRAME: 4,
  ERR_BAD_UTF8: 5,
  ERR_NO_ELEMENT: 6,
  ERR_PASTE_FRAME: 7,
  ERR_INGEST_REFUSED: 8,
  ERR_WELD_REFUSED: 9,
  ERR_NOTHING_UNDERSTOOD: 10,
  ERR_FIELD_VALUE: 11,
  ERR_EQUIP_FRAME: 12,
  ERR_EQUIP_STORE: 13,
  ERR_NO_DICTIONARY: 14,
  ERR_NO_LINK: 15,
  ERR_LINK_CHOICE: 16,
  ERR_PASTE_CHOICE: 17,
  ERR_CABLE_COUNT: 18,
  ERR_CABLE_END: 19,
  ERR_NO_CABLE: 20,
  ERR_PLAIN_REFUSED: 21,
} as const;

/** The FDLT reply header (`protocol.rs`'s `header()`, `HEADER_LEN`). */
export const REPLY_MAGIC = [0x46, 0x44, 0x4c, 0x54]; // "FDLT"
export const REPLY_VERSION = 1;
export const HEADER_LEN = 16;

/** Record kinds, and the fixed stride that goes with each. Kind 3 (finder
 * rows) is named for completeness of the table but is not decoded by this
 * client slice — the drawer never sends `OP_QUERY`. */
export const KIND_ERROR = 0;
export const KIND_FINDER_ROW = 3;
export const KIND_FACE_ROW = 5;

export const ERROR_STRIDE = 28;
export const FINDER_ROW_STRIDE = 88;
export const FACE_ROW_STRIDE = 72;
export const FACE_SLOTS = 8;

/** `dictframe.rs`'s role byte: which half of an `OP_DICT` file this is. */
export const DICT_ROLE_SOURCE = 0; // ROLE_DICT_SOURCE
export const DICT_ROLE_FIELD_KEYS = 1; // ROLE_FIELD_KEYS

type NumberTable = Record<string, number>;

function reverseLookup(table: NumberTable): Map<number, string> {
  const out = new Map<number, string>();
  for (const [name, value] of Object.entries(table)) {
    out.set(value, name);
  }
  return out;
}

const FACE_NAMES_BY_VALUE = reverseLookup(FACES);
const ERROR_NAMES_BY_VALUE = reverseLookup(ERRORS);

/** The face role's name from the table above, for callers that want to say
 * which face a row is rather than carry the bare number (WO-08 §4.4's "keyed
 * by face name", not a name-to-key table re-derived per caller). */
export function faceName(role: number): string | undefined {
  return FACE_NAMES_BY_VALUE.get(role);
}

export function errorName(code: number): string | undefined {
  return ERROR_NAMES_BY_VALUE.get(code);
}
