// Known-answer vectors, independently generated by
// `python3 crates/fathom-server/tests/vectors/gen_session_vectors.py` on
// 2026-09-14 (no committed usable values existed in that directory before
// this test; the tree under `tests/vectors/` held only the generator, so
// running it was the only way to get numbers to check against).
//
// The point, repeated from that script's own header: THIS FILE MUST NOT
// call anything this client's own `session.ts` exports and then compare the
// result to itself -- that would pass for any construction whatsoever,
// including a wrong one. Every constant below is copied by hand from the
// generator's output, which is itself an assembly independent of the Rust
// source, from the same specification. If `session.ts` and both of those
// agree, three readings of one specification laid the bytes out the same
// way.
import { describe, expect, it } from 'vitest';

import { fromHex, toHex } from './bytes';
import { bodyDigest, requestBytes, sessionChallenge } from './session';

const DEPLOYMENT_ID = '01JQZ0000000000000000000DD';
const SESSION_ID = '01JQZ0000000000000000000SS';
const SERVER_NONCE = fromHex('3131313131313131313131313131313131313131313131313131313131313131');
const REQUEST_NONCE = fromHex('3232323232323232323232323232323232323232323232323232323232323232');
const METHOD = 'GET';
const PATH = '/organisations/01JQZ0000000000000000000AA/capability?at=now';
const BODY = new TextEncoder().encode('the body this request actually carried');
const UNIX_MS = 1_760_000_000_123;
const REQUEST_COUNTER = 9;

const SESSION_PUBKEY = fromHex(
  '04462dba1ae4fc1a968b4dacf20cdd6dbe1fae34aa971514a63d3405c3d1cfd383b58bbb08c1' +
  '3383428c5853c71c4c851e134b056821e468fe0a977abf4313dde1',
);

const EXPECTED_SESSION_CHALLENGE = '316ad324a4f78a30c030b33885f7d05a43f242a3488553c468f93bf25578a984';
const EXPECTED_BODY_DIGEST = '30c5adaddc10b5c5a4e5753b214eb66c9c42dfdf44468c31bc70a6b666b1752d';
const EXPECTED_REQUEST_BYTES_RAW = fromHex(
  '15000000666174686f6d2f73657373696f6e2f7265712f76311a00000030314a515a30303030' +
  '3030303030303030303030303030305353030000004745543b0000002f6f7267616e69736174' +
  '696f6e732f30314a515a3030303030303030303030303030303030303041412f636170616269' +
  '6c6974793f61743d6e6f772000000030c5adaddc10b5c5a4e5753b214eb66c9c42dfdf44468c' +
  '31bc70a6b666b1752d2000000032323232323232323232323232323232323232323232323232' +
  '323232323232327bc02cc8990100000900000000000000',
);
const EXPECTED_REQUEST_BYTES = toHex(EXPECTED_REQUEST_BYTES_RAW);

// The Rust side's own signature over `REQUEST_BYTES`, produced by
// `SoftwareKey::sign` under RFC 6979 deterministic nonces and therefore a
// fixed value the Python script *verifies* rather than reproduces. Checking
// it again here, against `requestBytes()`'s own output, closes the loop
// across three independent implementations: if this client's byte layout
// drifted from the server's by even one length prefix, this signature would
// stop verifying.
const SIGNATURE_OVER_REQUEST_BYTES = fromHex(
  'f7287814e9e2082c43eed17e320b25e0f016c610aacfc187c5240cf1c7e8774b2f9108124295' +
  '71d9122bc2c1930fc96c843ebc1ab854444ba884b3f7702215df',
);

describe('session_challenge (crates/fathom-server/src/sessions.rs)', () => {
  it('matches the independently-generated vector', async () => {
    const digest = await sessionChallenge(SESSION_PUBKEY, SERVER_NONCE, DEPLOYMENT_ID);
    expect(toHex(digest)).toBe(EXPECTED_SESSION_CHALLENGE);
  });
});

describe('body_digest (crates/fathom-server/src/sessions.rs)', () => {
  it('matches the independently-generated vector', async () => {
    const digest = await bodyDigest(BODY);
    expect(toHex(digest)).toBe(EXPECTED_BODY_DIGEST);
  });
});

describe('request_bytes (crates/fathom-server/src/sessions.rs)', () => {
  it('matches the independently-generated vector, byte for byte', async () => {
    const digest = await bodyDigest(BODY);
    const bytes = requestBytes(SESSION_ID, METHOD, PATH, digest, REQUEST_NONCE, UNIX_MS, REQUEST_COUNTER);
    expect(toHex(bytes)).toBe(EXPECTED_REQUEST_BYTES);
  });

  it('verifies under the fixed session key and the signature the Rust signer produced', async () => {
    const digest = await bodyDigest(BODY);
    const bytes = requestBytes(SESSION_ID, METHOD, PATH, digest, REQUEST_NONCE, UNIX_MS, REQUEST_COUNTER);

    const publicKey = await crypto.subtle.importKey(
      'raw',
      SESSION_PUBKEY as BufferSource,
      { name: 'ECDSA', namedCurve: 'P-256' },
      false,
      ['verify'],
    );
    const verified = await crypto.subtle.verify(
      { name: 'ECDSA', hash: 'SHA-256' },
      publicKey,
      SIGNATURE_OVER_REQUEST_BYTES as BufferSource,
      bytes as BufferSource,
    );
    expect(verified).toBe(true);
  });
});
