//! Golden vectors for the browser's plain-face writer/reader, under
//! `client/src/document/vectors/`.
//!
//! ADR-0049 #3: *"the browser's writer is proved against Rust-made
//! vectors. A Rust test writes small graphs with `write_plain` into fixtures
//! under the client tree, and the TypeScript reader and writer must
//! reproduce them byte for byte -- the same cross-language pattern as the
//! session vectors."*
//!
//! **How this relates to `tests/session_vectors.rs` and its generator**,
//! since that is the pattern this follows: `tests/vectors/gen_session_vectors.py`
//! is a second, independent assembly of the same wire values, and
//! `session_vectors.rs` pastes its output as Rust constants so two unrelated
//! implementations can be checked against each other without either reading
//! the other's source. There is no second implementation of `write_plain`
//! yet -- the TypeScript side does not exist -- so there is nothing to paste
//! constants from. What this file plays the generator's role for instead is
//! the FIXTURE FILES THEMSELVES: [`write_client_vectors`] is the one-shot
//! generator (marked `#[ignore]`, exactly as a generator that writes output
//! rather than running as part of every `cargo test` should be, with a
//! `--nocapture` path printing where each file landed), and the checked-in
//! `.plain` files it produces are what a future TypeScript reader/writer is
//! proved against, the same way `PINNED` in `tests/plain_face.rs` is typed
//! from a document rather than regenerated by the code it checks.
//!
//! Run it with:
//! ```text
//! cargo test -p fathom-workspace --test generate_client_vectors -- --ignored --nocapture
//! ```
//!
//! Every value in every graph below is a SAMPLE, not a fixed convention --
//! each `.json` sidecar says so in its own words, per the brief. Kinds, edge
//! kinds and field names are copied from `schema/schema.yaml` (the `Rack`,
//! `Chassis`, `Device`, `PhysicalPort` kinds and the `HasRack`, `HasChassis`,
//! `MountedIn`, `HasPort` edges), not invented here.

use std::fs;
use std::path::PathBuf;

use fathom_graph::{
    Actor, BatchId, Confidence, ElementId, Graph, NodeId, Origin, ProvenanceId, ProvenanceRecord,
    Timestamp, UserId,
};
use fathom_id::Ulid;
use fathom_ir::generated::ir_types::{
    EdgeKind, MountedInFace, MountedInField, NodeKind, PhysicalPortConnector, PhysicalPortField,
    RackField, RackUnitNumbering,
};
use fathom_ir::scalar::Text;
use fathom_ir::value::PortPosition;
use fathom_workspace::{read_plain, write_plain};

// ---------------------------------------------------------------------------
// Fixed provenance, exactly `tests/plain_face.rs`'s own pattern -- copied
// rather than shared, since integration test files are separate crates.
// ---------------------------------------------------------------------------

const AT: u64 = 1_700_000_000_000;

fn ulid(n: u128) -> Ulid {
    Ulid::from_parts(AT, n).expect("48-bit timestamp")
}

fn prov(n: u128) -> ProvenanceRecord {
    ProvenanceRecord {
        id: ProvenanceId(ulid(1_000_000 + n)),
        origin: Origin::Hand,
        asserted_at: Timestamp(AT),
        asserted_by: Actor::User(UserId(ulid(u128::MAX))),
        confidence: Confidence::Asserted,
        supersedes: None,
    }
}

// ---------------------------------------------------------------------------
// The three graphs
// ---------------------------------------------------------------------------

/// Vector 1: a graph with nothing in it.
fn empty_graph() -> Graph {
    Graph::new()
}

/// A `Premises` and a `Rack` joined by `HasRack`, with the rack carrying
/// `label`, `height_u` and `unit_numbering` -- the shared body of vectors 2
/// and 3.
fn premises_and_rack(g: &mut Graph, seed: u128) -> (NodeId, NodeId) {
    let premises = g
        .insert_node(NodeKind::Premises, ulid(seed), prov(seed + 1))
        .expect("premises");
    let rack = g
        .insert_node(NodeKind::Rack, ulid(seed + 2), prov(seed + 3))
        .expect("rack");
    g.insert_edge(
        EdgeKind::HasRack,
        ulid(seed + 4),
        premises,
        rack,
        prov(seed + 5),
    )
    .expect("has rack");
    g.set_field(
        ElementId::Node(rack),
        RackField::Label.key(),
        Text("R1".to_owned()),
        prov(seed + 6),
    )
    .expect("rack label");
    g.set_field(
        ElementId::Node(rack),
        RackField::HeightU.key(),
        42u8,
        prov(seed + 7),
    )
    .expect("rack height_u");
    g.set_field(
        ElementId::Node(rack),
        RackField::UnitNumbering.key(),
        RackUnitNumbering::Ascending,
        prov(seed + 8),
    )
    .expect("rack unit_numbering");
    (premises, rack)
}

/// Vector 2: one `Premises`, one `Rack` (`label`, `height_u` 42,
/// `unit_numbering`), joined by `HasRack`.
fn one_rack_graph() -> Graph {
    let mut g = Graph::new();
    g.begin_batch(BatchId(ulid(0)), "one rack")
        .expect("open batch");
    premises_and_rack(&mut g, 1);
    g.end_batch().expect("close batch");
    g
}

/// Vector 3: the rack above, plus two `Device` nodes each with one
/// `Chassis` (`HasChassis`), each chassis `MountedIn` the rack at a
/// different `position_u` with `face` set, and each chassis with a
/// handful of `PhysicalPort` nodes via `HasPort` carrying `label`,
/// `position` and `connector`.
fn two_chassis_graph() -> Graph {
    let mut g = Graph::new();
    g.begin_batch(BatchId(ulid(0)), "two chassis in a rack")
        .expect("open batch");
    let (_premises, rack) = premises_and_rack(&mut g, 1);

    // (device/chassis seed base, position_u, face, port connectors)
    let chassis_plan: [(u128, u8, MountedInFace, &[PhysicalPortConnector]); 2] = [
        (
            100,
            10,
            MountedInFace::Front,
            &[PhysicalPortConnector::Rj45, PhysicalPortConnector::Rj45],
        ),
        (
            200,
            20,
            MountedInFace::Rear,
            &[
                PhysicalPortConnector::SfpPlus,
                PhysicalPortConnector::SfpPlus,
                PhysicalPortConnector::Qsfp28,
            ],
        ),
    ];

    for (seed, position_u, face, connectors) in chassis_plan {
        let device = g
            .insert_node(NodeKind::Device, ulid(seed), prov(seed + 1))
            .expect("device");
        let chassis = g
            .insert_node(NodeKind::Chassis, ulid(seed + 2), prov(seed + 3))
            .expect("chassis");
        g.insert_edge(
            EdgeKind::HasChassis,
            ulid(seed + 4),
            device,
            chassis,
            prov(seed + 5),
        )
        .expect("has chassis");

        let mounted = g
            .insert_edge(
                EdgeKind::MountedIn,
                ulid(seed + 6),
                chassis,
                rack,
                prov(seed + 7),
            )
            .expect("mounted in");
        g.set_field(
            ElementId::Edge(mounted),
            MountedInField::PositionU.key(),
            position_u,
            prov(seed + 8),
        )
        .expect("position_u");
        g.set_field(
            ElementId::Edge(mounted),
            MountedInField::Face.key(),
            face,
            prov(seed + 9),
        )
        .expect("face");

        for (i, connector) in connectors.iter().enumerate() {
            let port_seed = seed + 20 + (i as u128) * 10;
            let port = g
                .insert_node(NodeKind::PhysicalPort, ulid(port_seed), prov(port_seed + 1))
                .expect("port");
            g.insert_edge(
                EdgeKind::HasPort,
                ulid(port_seed + 2),
                chassis,
                port,
                prov(port_seed + 3),
            )
            .expect("has port");
            g.set_field(
                ElementId::Node(port),
                PhysicalPortField::Label.key(),
                Text((i + 1).to_string()),
                prov(port_seed + 4),
            )
            .expect("port label");
            // `PortPosition` is a field-less stub -- 19 §3.3's shape is not
            // modelled yet (`fathom-ir`'s own note on `value::PortPosition`)
            // -- so setting it records only that a position is known, wire
            // form `{}`. See the sidecar for this vector.
            g.set_field(
                ElementId::Node(port),
                PhysicalPortField::Position.key(),
                PortPosition,
                prov(port_seed + 5),
            )
            .expect("port position");
            g.set_field(
                ElementId::Node(port),
                PhysicalPortField::Connector.key(),
                connector.clone(),
                prov(port_seed + 6),
            )
            .expect("port connector");
        }
    }

    g.end_batch().expect("close batch");
    g
}

// ---------------------------------------------------------------------------
// Sanity: every vector graph is a valid `fathom-plain` document, whether or
// not the generator below has ever been run. Cheap, and runs every
// `cargo test`.
// ---------------------------------------------------------------------------

#[test]
fn every_client_vector_graph_round_trips_byte_identical() {
    for g in [empty_graph(), one_rack_graph(), two_chassis_graph()] {
        let first = write_plain(&g).expect("writes");
        let reloaded = read_plain(&first).expect("reads");
        let second = write_plain(&reloaded).expect("writes again");
        assert_eq!(
            first, second,
            "write -> read -> write must be byte-identical"
        );
    }
}

// ---------------------------------------------------------------------------
// The generator
// ---------------------------------------------------------------------------

fn client_vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../client/src/document/vectors")
}

/// One fixture: the bytes and the plain-words sidecar describing them.
struct Vector {
    name: &'static str,
    bytes: Vec<u8>,
    sidecar: String,
}

fn sidecar(
    name: &str,
    description: &str,
    node_count: usize,
    edge_count: usize,
    kinds: &[&str],
    edges: &[&str],
) -> String {
    let kinds_json = kinds
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let edges_json = edges
        .iter()
        .map(|e| format!("\"{e}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{\n  \"name\": \"{name}\",\n  \"description\": \"{description}\",\n  \"node_count\": \
         {node_count},\n  \"edge_count\": {edge_count},\n  \"kinds\": [{kinds_json}],\n  \
         \"edges\": [{edges_json}]\n}}\n"
    )
}

/// The one-shot generator (ADR-0049 #3). `--ignored`: this writes files
/// under the client tree, which `cargo test` must not do on every run.
/// `--nocapture` to see where each vector landed.
#[test]
#[ignore = "writes client/src/document/vectors/ -- run explicitly, see this file's module doc"]
fn write_client_vectors() {
    let vectors = vec![
        Vector {
            name: "empty",
            bytes: write_plain(&empty_graph()).expect("writes"),
            sidecar: sidecar(
                "empty",
                "A graph with nothing in it: no nodes, no edges, no batches, no history, no \
                 provenance. This is the whole document, not a placeholder for one.",
                0,
                0,
                &[],
                &[],
            ),
        },
        Vector {
            name: "one-rack",
            bytes: write_plain(&one_rack_graph()).expect("writes"),
            sidecar: sidecar(
                "one-rack",
                "One Premises node and one Rack node, joined by a HasRack edge. The Rack \
                 carries label \\\"R1\\\", height_u 42 and unit_numbering \\\"ascending\\\". \
                 Every value is a sample: a real design could give the rack any label, any \
                 height_u in Rack's declared range 1..100, and either unit_numbering.",
                2,
                1,
                &["Premises", "Rack"],
                &["HasRack"],
            ),
        },
        Vector {
            name: "two-chassis",
            bytes: write_plain(&two_chassis_graph()).expect("writes"),
            sidecar: sidecar(
                "two-chassis",
                "Builds on one-rack.plain: the same Premises and Rack (label \\\"R1\\\", \
                 height_u 42, ascending), plus two Device nodes, each with one Chassis \
                 (HasChassis). Each chassis is MountedIn the rack at a different position_u \
                 (10 and 20) with face set (front and rear -- both sampled, not a rule: \
                 MountedIn.face is optional and either value is legal). The first chassis \
                 owns 2 PhysicalPort nodes, the second owns 3, each attached via HasPort and \
                 carrying a label (\\\"1\\\", \\\"2\\\", ...), a position and a connector \
                 (rj45, sfp_plus, qsfp28 -- sampled from PhysicalPort.connector's closed \
                 vocabulary, not the only legal values). PhysicalPort.position is set on \
                 every port, but 19 section 3.3's PortPosition shape has no modelled fields yet \
                 (fathom-ir's own value::PortPosition stub), so on the wire it is the empty \
                 object {}; setting it records only that a position is known, not what it is. \
                 Every label, position_u, face and connector value here is a sample, never a \
                 fixed convention.",
                11,
                10,
                &["Premises", "Rack", "Device", "Chassis", "PhysicalPort"],
                &["HasRack", "HasChassis", "MountedIn", "HasPort"],
            ),
        },
    ];

    let dir = client_vectors_dir();
    fs::create_dir_all(&dir).unwrap_or_else(|e| panic!("could not create {}: {e}", dir.display()));

    for vector in vectors {
        let plain_path = dir.join(format!("{}.plain", vector.name));
        let json_path = dir.join(format!("{}.json", vector.name));
        fs::write(&plain_path, &vector.bytes)
            .unwrap_or_else(|e| panic!("could not write {}: {e}", plain_path.display()));
        fs::write(&json_path, vector.sidecar.as_bytes())
            .unwrap_or_else(|e| panic!("could not write {}: {e}", json_path.display()));
        println!(
            "wrote {} ({} bytes)",
            plain_path.display(),
            vector.bytes.len()
        );
        println!("wrote {}", json_path.display());
    }
}
