//! Emitters for the two generated Rust files in `fathom-ir`.
//!
//! Both files wrap their items in `#[rustfmt::skip] mod body { .. }` and
//! re-export: the checked-in bytes must be a function of the schema tree
//! alone, and rustfmt's wrapping decisions would otherwise join the input
//! set (CI byte-compares these files — `schema.codegen.stale`). The emitted
//! style is kept conventional anyway; the attribute is a determinism seal,
//! not an excuse.

use crate::extract::{
    camel, rust_ident, snake, EdgeGen, ExtractError, Extracted, FieldGen, FieldTy,
};
use std::collections::BTreeSet;
use std::fmt::Write;

/// The header every generated file opens with. No timestamp — determinism.
pub const HEADER: &str = "GENERATED by fathom-schemagen from schema/ — do not edit; see 62 §17";

fn doc_lines(out: &mut String, indent: &str, lines: &[String]) {
    for l in lines {
        if l.is_empty() {
            let _ = writeln!(out, "{indent}///");
        } else {
            let _ = writeln!(out, "{indent}/// {l}");
        }
    }
}

/// Refuse duplicate generated type names — a collision would be a silently
/// shadowing defect, so it is a named refusal instead.
fn claim(names: &mut BTreeSet<String>, name: &str) -> Result<(), ExtractError> {
    if names.insert(name.to_owned()) {
        Ok(())
    } else {
        Err(ExtractError(format!(
            "generated type name `{name}` collides with an earlier one"
        )))
    }
}

// ---------------------------------------------------------------------------
// ir_types.rs

pub fn ir_types(x: &Extracted) -> Result<String, ExtractError> {
    let mut names: BTreeSet<String> = BTreeSet::new();
    for n in [
        "Layer",
        "EdgeClass",
        "NodeKind",
        "EdgeKind",
        "DerivedEdgeKind",
    ] {
        claim(&mut names, n)?;
    }

    let mut o = String::new();
    let _ = writeln!(o, "// {HEADER}.");
    o.push_str(
        "\n//! Generated IR types (62 §17.1): the kind/edge enums \
         (`EnumMap`-compatible:\n//! dense, `Copy`, `COUNT` + `index`), schema \
         enums with generated unknown\n//! arms (62 §7 rule 2), per-kind and \
         per-edge field enums keyed by the\n//! wire registry, the field-key \
         table, and the scalar-binding inventory\n//! that makes `cargo build` \
         the compile-time half of `schema.scalar.unbound`.\n\n",
    );
    o.push_str("#[rustfmt::skip]\nmod body {\n");

    // ---- closed vocabularies ----------------------------------------------
    o.push_str(
        "    /// The closed layer vocabulary (62 §4.2; 19 §2.2). Drives emit \
         exclusion,\n    /// the re-identification scope filter, the diagram \
         layer mask and the\n    /// inventory kind lists — four consumers, \
         mechanically, nothing ad hoc.\n",
    );
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    o.push_str(
        "    pub enum Layer {\n        Config,\n        Physical,\n        Service,\n    }\n\n",
    );
    o.push_str(
        "    /// The closed asserted-edge class vocabulary (62 §6.2): \
         containment\n    /// builds the forest, reference never deletes its \
         target. Derived edges\n    /// have no class — separate arena \
         (62 §11.4).\n",
    );
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    o.push_str("    pub enum EdgeClass {\n        Containment,\n        Reference,\n    }\n\n");

    o.push_str(
        "    /// An L0 cardinality bound (62 §6.2). `min` is recorded for L1's \
         later use;\n    /// only `max` is enforced at write time (11 §7.1). A \
         `None` max is the\n    /// `n` token — unbounded.\n",
    );
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    o.push_str("    pub struct EdgeCardBound { pub min: u32, pub max: Option<u32> }\n\n");

    // ---- NodeKind ----------------------------------------------------------
    o.push_str(
        "    /// Node kinds, declaration order (62 §2.3 — the deterministic \
         iteration\n    /// order invariant 9 relies on). Dense and `Copy` for \
         `EnumMap`; unknown\n    /// kinds are the store's preserve-mode \
         business, not a variant, because\n    /// `NodeId` embeds a `Copy` \
         `NodeKind` (62 §13.1).\n",
    );
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    o.push_str("    pub enum NodeKind {\n");
    for k in &x.kinds {
        doc_lines(&mut o, "        ", &k.doc);
        let _ = writeln!(o, "        {},", k.name);
    }
    o.push_str("    }\n\n");
    o.push_str("    impl NodeKind {\n");
    let _ = writeln!(o, "        pub const COUNT: usize = {};", x.kinds.len());
    o.push_str("        /// Every kind, declaration order.\n");
    let _ = writeln!(
        o,
        "        pub const ALL: [NodeKind; {}] = [",
        x.kinds.len()
    );
    for k in &x.kinds {
        let _ = writeln!(o, "            NodeKind::{},", k.name);
    }
    o.push_str("        ];\n");
    o.push_str("        /// Dense index, declaration order — the `EnumMap` key.\n");
    o.push_str("        pub const fn index(self) -> usize { self as usize }\n");
    o.push_str("        /// The declared kind name.\n");
    o.push_str("        pub const fn name(self) -> &'static str {\n            match self {\n");
    for k in &x.kinds {
        let _ = writeln!(o, "                NodeKind::{} => \"{}\",", k.name, k.name);
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        pub fn from_name(name: &str) -> Option<NodeKind> {\n            match name {\n",
    );
    for k in &x.kinds {
        let _ = writeln!(
            o,
            "                \"{}\" => Some(NodeKind::{}),",
            k.name, k.name
        );
    }
    o.push_str("                _ => None,\n            }\n        }\n");
    o.push_str("        /// The kind's layer (62 §4.2).\n");
    o.push_str("        pub const fn layer(self) -> Layer {\n            match self {\n");
    for k in &x.kinds {
        let _ = writeln!(
            o,
            "                NodeKind::{} => Layer::{},",
            k.name,
            k.layer.variant()
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        /// Whether the kind participates in emit at all (62 §4.2); \
         `false`\n        /// excludes it from every emit unit and coverage \
         report.\n",
    );
    o.push_str("        pub const fn emits(self) -> bool {\n            match self {\n");
    for k in &x.kinds {
        let _ = writeln!(o, "                NodeKind::{} => {},", k.name, k.emits);
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        /// The kind's declared field keys, declaration order \
         (62 §4.3). A key\n        /// outside this slice is not a field of \
         this kind, which is what a\n        /// store checks a write against \
         (ADR-0008 at the write boundary).\n",
    );
    o.push_str(
        "        pub const fn fields(self) -> &'static [crate::bag::FieldKey] {\n            match self {\n",
    );
    for k in &x.kinds {
        let mut keys = String::new();
        for (i, f) in k.fields.iter().enumerate() {
            if i > 0 {
                keys.push_str(", ");
            }
            let _ = write!(
                keys,
                "crate::bag::FieldKey({})",
                x.field_key(&k.name, &f.name)?
            );
        }
        let _ = writeln!(o, "                NodeKind::{} => &[{keys}],", k.name);
    }
    o.push_str("            }\n        }\n");
    o.push_str("    }\n\n");

    // ---- EdgeKind / DerivedEdgeKind ---------------------------------------
    edge_kind_enum(
        &mut o,
        "EdgeKind",
        &x.edges,
        "    /// Asserted edge kinds, declaration order. Derived edges are \
         deliberately\n    /// a separate enum: they live in a separate arena \
         and the store must\n    /// refuse to serialise them (62 §11.4) — a \
         shared enum invites exactly\n    /// that defect.\n",
    );
    edge_kind_enum(
        &mut o,
        "DerivedEdgeKind",
        &x.derived_edges,
        "    /// Derived edge kinds, declaration order (62 §11.4): rebuilt on \
         load and\n    /// after every mutation batch, never serialised, never \
         merged, never\n    /// edited.\n",
    );
    edge_tables(&mut o, x)?;

    // ---- schema enums (files) ---------------------------------------------
    for e in &x.enums {
        claim(&mut names, &e.rust_name)?;
        let mut variants: Vec<(String, String)> = Vec::new(); // (variant, token)
        for t in &e.variants {
            let v = camel(t)?;
            if v == "Unknown" {
                // The gate schema.enum.reserved-variant forbids this on
                // enum files; reaching here means the gates regressed.
                return Err(ExtractError(format!(
                    "enum file `{}` declares reserved variant `{t}`",
                    e.stem
                )));
            }
            variants.push((v, t.clone()));
        }
        named_enum(&mut o, &e.rust_name, &variants, None, &{
            let mut doc = vec![format!("`schema/enums/{}.yaml`.", e.stem)];
            doc.extend(enum_doc(&e.node));
            doc
        })?;
    }

    // ---- inline enums ------------------------------------------------------
    for ie in &x.inline_enums {
        claim(&mut names, &ie.rust_name)?;
        let mut variants: Vec<(String, String)> = Vec::new();
        let mut folded: Option<String> = None;
        for t in &ie.variants {
            let v = camel(t)?;
            if v == "Unknown" {
                // The shipped tree's Link.media declares `unknown` (its own
                // filed form-vs-content collision with 62 §7 rule 2). The
                // declared variant folds into the generated arm: the token
                // round-trips through `Unknown("unknown")`, nothing collides,
                // and DECLARED still lists it as the schema fact it is.
                folded = Some(t.clone());
            } else {
                variants.push((v, t.clone()));
            }
        }
        let doc = vec![format!(
            "Inline enum on `{}.{}` (62 §7 rule 4; codegen-named).",
            ie.owner, ie.field
        )];
        named_enum_with_declared(
            &mut o,
            &ie.rust_name,
            &variants,
            &ie.variants,
            folded.as_deref(),
            &doc,
        )?;
    }

    // ---- per-kind and per-edge field enums --------------------------------
    for k in &x.kinds {
        let ename = format!("{}Field", k.name);
        claim(&mut names, &ename)?;
        field_enum(&mut o, x, &ename, &k.name, &k.fields, "kind")?;
    }
    for e in x.edges.iter().chain(&x.derived_edges) {
        if e.fields.is_empty() {
            continue;
        }
        let ename = format!("{}Field", e.name);
        claim(&mut names, &ename)?;
        field_enum(&mut o, x, &ename, &e.name, &e.fields, "edge")?;
    }

    // ---- the field-key table ----------------------------------------------
    o.push_str(
        "    /// The field-key registry, declaration order (62 §17.1): stable \
         integer\n    /// keys per field, append-only, keys never reused. \
         Mirrored in\n    /// `schema.json`; the wire format's field \
         addressing (11 §14.1).\n",
    );
    let _ = writeln!(
        o,
        "    pub const FIELD_KEYS: [(&str, u32); {}] = [",
        x.field_keys.len()
    );
    for (name, key) in &x.field_keys {
        let _ = writeln!(o, "        (\"{name}\", {key}),");
    }
    o.push_str("    ];\n\n");

    // ---- the scalar-binding inventory -------------------------------------
    o.push_str(
        "    /// 62 §18.1 `schema.scalar.unbound`, compile-time half: every \
         `impl:`\n    /// path bound in the `scalars:` block is referenced \
         here by its declared\n    /// path, so a binding that does not \
         resolve fails `cargo build` of this\n    /// crate. Trait conformance \
         is the deferred half — the `Scalar` trait\n    /// (11 §4.2) does not \
         exist yet; `scalar`/`value` are stubs, marked so.\n",
    );
    o.push_str("    #[allow(dead_code)]\n    fn scalar_bindings_resolve() {\n");
    for s in &x.scalars {
        let crate_path = s
            .impl_path
            .strip_prefix("fathom_ir::")
            .expect("validated at extract");
        let _ = writeln!(
            o,
            "        let _ = core::mem::size_of::<crate::{crate_path}>();"
        );
    }
    o.push_str("        // The registered builtin exception (11 §6.5):\n");
    o.push_str("        let _ = core::mem::size_of::<fathom_id::NodeId>();\n");
    o.push_str("    }\n");

    o.push_str("}\npub use body::*;\n");
    Ok(o)
}

fn edge_kind_enum(o: &mut String, name: &str, edges: &[EdgeGen], doc: &str) {
    o.push_str(doc);
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    let _ = writeln!(o, "    pub enum {name} {{");
    for e in edges {
        doc_lines(o, "        ", &e.doc);
        let _ = writeln!(o, "        {},", e.name);
    }
    o.push_str("    }\n\n");
    let _ = writeln!(o, "    impl {name} {{");
    let _ = writeln!(o, "        pub const COUNT: usize = {};", edges.len());
    o.push_str("        /// Every kind, declaration order.\n");
    let _ = writeln!(o, "        pub const ALL: [{name}; {}] = [", edges.len());
    for e in edges {
        let _ = writeln!(o, "            {name}::{},", e.name);
    }
    o.push_str("        ];\n");
    o.push_str("        /// Dense index, declaration order — the `EnumMap` key.\n");
    o.push_str("        pub const fn index(self) -> usize { self as usize }\n");
    o.push_str("        /// The declared edge name.\n");
    o.push_str("        pub const fn name(self) -> &'static str {\n            match self {\n");
    for e in edges {
        let _ = writeln!(o, "                {name}::{} => \"{}\",", e.name, e.name);
    }
    o.push_str("            }\n        }\n");
    let _ = writeln!(
        o,
        "        pub fn from_name(name: &str) -> Option<{name}> {{\n            match name {{"
    );
    for e in edges {
        let _ = writeln!(
            o,
            "                \"{}\" => Some({name}::{}),",
            e.name, e.name
        );
    }
    o.push_str("                _ => None,\n            }\n        }\n");
    if edges.iter().all(|e| e.class.is_some()) {
        o.push_str(
            "        /// Containment builds the forest; reference never deletes (62 §6.2).\n",
        );
        o.push_str("        pub const fn class(self) -> EdgeClass {\n            match self {\n");
        for e in edges {
            let _ = writeln!(
                o,
                "                {name}::{} => EdgeClass::{},",
                e.name,
                e.class.expect("checked").variant()
            );
        }
        o.push_str("            }\n        }\n");
    }
    if edges.iter().all(|e| e.produced_by.is_some()) {
        o.push_str("        /// The producing inference pass (`InferenceRuleId`, 62 §11.4).\n");
        o.push_str(
            "        pub const fn produced_by(self) -> &'static str {\n            match self {\n",
        );
        for e in edges {
            let _ = writeln!(
                o,
                "                {name}::{} => \"{}\",",
                e.name,
                e.produced_by.as_deref().expect("checked")
            );
        }
        o.push_str("            }\n        }\n");
    }
    o.push_str("    }\n\n");
}

/// The static schema tables an L0-enforcing store reads: endpoint kind sets,
/// both L0 cardinality bounds, the symmetric flag, the root-containment flag
/// and the declared field keys. Every one of these is a schema fact
/// (62 §6.2); generating them is what keeps a store from hand-copying one
/// (ADR-0008).
fn edge_tables(o: &mut String, x: &Extracted) -> Result<(), ExtractError> {
    let bound = |b: &(u32, Option<u32>)| -> String {
        let max = match b.1 {
            Some(m) => format!("Some({m})"),
            None => "None".to_owned(),
        };
        format!("EdgeCardBound {{ min: {}, max: {max} }}", b.0)
    };
    let kind_list = |names: &[String]| -> String {
        let mut s = String::new();
        for (i, n) in names.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            let _ = write!(s, "NodeKind::{n}");
        }
        s
    };

    o.push_str("    impl EdgeKind {\n");
    o.push_str(
        "        /// The declared `from:` kind set, class names expanded \
         (62 §6.2).\n        /// Empty exactly when `root_containment()` — the \
         workspace root is not\n        /// a node, so it is not in the \
         `NodeKind` vocabulary.\n",
    );
    o.push_str(
        "        pub const fn from_kinds(self) -> &'static [NodeKind] {\n            match self {\n",
    );
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => &[{}],",
            e.name,
            kind_list(&e.from_kinds)
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str("        /// The declared `to:` kind set, class names expanded (62 §6.2).\n");
    o.push_str(
        "        pub const fn to_kinds(self) -> &'static [NodeKind] {\n            match self {\n",
    );
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => &[{}],",
            e.name,
            kind_list(&e.to_kinds)
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        /// The `out:` bound at L0 — edges leaving a `from` node \
         (11 §7.1).\n",
    );
    o.push_str(
        "        pub const fn out_bound_l0(self) -> EdgeCardBound {\n            match self {\n",
    );
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => {},",
            e.name,
            bound(&e.out_l0)
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str("        /// The `in:` bound at L0 — edges arriving at a `to` node (11 §7.1).\n");
    o.push_str(
        "        pub const fn in_bound_l0(self) -> EdgeCardBound {\n            match self {\n",
    );
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => {},",
            e.name,
            bound(&e.in_l0)
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        /// `true` means `(a,b)` and `(b,a)` are the same edge: one \
         stored\n        /// instance, canonical order by `NodeId` (62 §6.2; \
         11 §7.4).\n",
    );
    o.push_str("        pub const fn symmetric(self) -> bool {\n            match self {\n");
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => {},",
            e.name, e.symmetric
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str(
        "        /// `from: [root]` — containment by the workspace root \
         (11 §7.2).\n",
    );
    o.push_str("        pub const fn root_containment(self) -> bool {\n            match self {\n");
    for e in &x.edges {
        let _ = writeln!(
            o,
            "                EdgeKind::{} => {},",
            e.name, e.root_from
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str("        /// The edge's declared field keys, declaration order (62 §6.2).\n");
    o.push_str(
        "        pub const fn fields(self) -> &'static [crate::bag::FieldKey] {\n            match self {\n",
    );
    for e in &x.edges {
        let mut keys = String::new();
        for (i, f) in e.fields.iter().enumerate() {
            if i > 0 {
                keys.push_str(", ");
            }
            let _ = write!(
                keys,
                "crate::bag::FieldKey({})",
                x.field_key(&e.name, &f.name)?
            );
        }
        let _ = writeln!(o, "                EdgeKind::{} => &[{keys}],", e.name);
    }
    o.push_str("            }\n        }\n");
    o.push_str("    }\n\n");
    Ok(())
}

/// Pull an enum file's `doc:` for the generated type's comment.
fn enum_doc(node: &fathom_schema::value::Node) -> Vec<String> {
    node.get("doc")
        .and_then(|d| d.as_str())
        .map(|d| d.lines().map(|l| l.trim_end().to_owned()).collect())
        .unwrap_or_default()
}

fn named_enum(
    o: &mut String,
    name: &str,
    variants: &[(String, String)],
    folded: Option<&str>,
    doc: &[String],
) -> Result<(), ExtractError> {
    let declared: Vec<String> = variants.iter().map(|(_, t)| t.clone()).collect();
    named_enum_with_declared(o, name, variants, &declared, folded, doc)
}

/// A schema enum: declared variants plus the generated `Unknown(String)` arm
/// (62 §7 rule 2). `declared` is the full token list for the `DECLARED`
/// const (it may include a folded `unknown` token, which stays a schema fact
/// even when it emits no arm of its own).
fn named_enum_with_declared(
    o: &mut String,
    name: &str,
    variants: &[(String, String)],
    declared: &[String],
    folded: Option<&str>,
    doc: &[String],
) -> Result<(), ExtractError> {
    {
        let mut seen = BTreeSet::new();
        for (v, _) in variants {
            if !seen.insert(v.clone()) {
                return Err(ExtractError(format!(
                    "enum `{name}`: two tokens camel-case to `{v}`"
                )));
            }
        }
    }
    doc_lines(o, "    ", doc);
    o.push_str("    #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    let _ = writeln!(o, "    pub enum {name} {{");
    for (v, _) in variants {
        let _ = writeln!(o, "        {v},");
    }
    o.push_str("        /// The generated unknown arm (62 §7 rule 2) — carries the\n");
    o.push_str("        /// unrecognised token verbatim; what makes a new variant a minor\n");
    o.push_str("        /// bump an old client survives (62 §16.2).\n");
    if let Some(t) = folded {
        let _ = writeln!(
            o,
            "        /// The declared `{t}` variant folds in here (the tree's own filed"
        );
        o.push_str("        /// collision with rule 2): its token round-trips as the payload.\n");
    }
    o.push_str("        Unknown(String),\n    }\n\n");
    let _ = writeln!(o, "    impl {name} {{");
    o.push_str("        /// Declared tokens, declaration order.\n");
    let _ = writeln!(
        o,
        "        pub const DECLARED: [&'static str; {}] = [",
        declared.len()
    );
    for t in declared {
        let _ = writeln!(o, "            \"{t}\",");
    }
    o.push_str("        ];\n");
    o.push_str("        /// Neutral token → variant; anything undeclared lands in `Unknown`.\n");
    let _ = writeln!(
        o,
        "        pub fn from_token(token: &str) -> {name} {{\n            match token {{"
    );
    for (v, t) in variants {
        let _ = writeln!(o, "                \"{t}\" => {name}::{v},");
    }
    let _ = writeln!(
        o,
        "                other => {name}::Unknown(other.to_owned()),"
    );
    o.push_str("            }\n        }\n");
    o.push_str("        /// The neutral token (the carried one for `Unknown`).\n");
    o.push_str("        pub fn token(&self) -> &str {\n            match self {\n");
    for (v, t) in variants {
        let _ = writeln!(o, "                {name}::{v} => \"{t}\",");
    }
    let _ = writeln!(o, "                {name}::Unknown(t) => t,");
    o.push_str("            }\n        }\n");
    o.push_str("    }\n\n");
    Ok(())
}

fn field_enum(
    o: &mut String,
    x: &Extracted,
    ename: &str,
    owner: &str,
    fields: &[FieldGen],
    what: &str,
) -> Result<(), ExtractError> {
    let mut variants: Vec<(String, &FieldGen)> = Vec::new();
    let mut seen = BTreeSet::new();
    for f in fields {
        let v = camel(&f.name)?;
        if !seen.insert(v.clone()) {
            return Err(ExtractError(format!(
                "`{owner}`: two fields camel-case to `{v}`"
            )));
        }
        variants.push((v, f));
    }
    let _ = writeln!(
        o,
        "    /// Fields of {what} `{owner}`, declaration order, keyed by the wire registry."
    );
    o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    let _ = writeln!(o, "    pub enum {ename} {{");
    for (v, _) in &variants {
        let _ = writeln!(o, "        {v},");
    }
    o.push_str("    }\n\n");
    let _ = writeln!(o, "    impl {ename} {{");
    let _ = writeln!(o, "        pub const COUNT: usize = {};", variants.len());
    o.push_str("        /// Every field, declaration order.\n");
    let _ = writeln!(
        o,
        "        pub const ALL: [{ename}; {}] = [",
        variants.len()
    );
    for (v, _) in &variants {
        let _ = writeln!(o, "            {ename}::{v},");
    }
    o.push_str("        ];\n");
    o.push_str("        /// Dense index, declaration order — the `EnumMap` key.\n");
    o.push_str("        pub const fn index(self) -> usize { self as usize }\n");
    o.push_str("        /// The declared field name.\n");
    o.push_str("        pub const fn name(self) -> &'static str {\n            match self {\n");
    for (v, f) in &variants {
        let _ = writeln!(o, "                {ename}::{v} => \"{}\",", f.name);
    }
    o.push_str("            }\n        }\n");
    o.push_str("        /// The stable wire key (`schema/field-keys.yaml`).\n");
    o.push_str(
        "        pub const fn key(self) -> crate::bag::FieldKey {\n            match self {\n",
    );
    for (v, f) in &variants {
        let key = x.field_key(owner, &f.name)?;
        let _ = writeln!(
            o,
            "                {ename}::{v} => crate::bag::FieldKey({key}),"
        );
    }
    o.push_str("            }\n        }\n");
    o.push_str("    }\n\n");
    Ok(())
}

// ---------------------------------------------------------------------------
// accessors.rs

pub fn accessors(x: &Extracted) -> Result<String, ExtractError> {
    let mut o = String::new();
    let _ = writeln!(o, "// {HEADER}.");
    o.push_str(
        "\n//! Typed fallible accessors per (kind, field) — 62 §17.1's \
         `accessors.rs`\n//! row, ADR-0007's mitigation for fallible field \
         reads made checkable: one\n//! function per kind field, generic over \
         `crate::bag::FieldBag`, returning\n//! the schema-declared type or a \
         precise `FieldError`. Reading a field a\n//! kind does not declare is \
         a compile error — the function does not exist.\n//! Edge-field reads \
         land with the emitter work (13).\n\n",
    );
    o.push_str("#[rustfmt::skip]\nmod body {\n");
    for k in &x.kinds {
        let module = rust_ident(&snake(&k.name));
        let _ = writeln!(o, "    /// Typed reads for `{}` fields.", k.name);
        let _ = writeln!(o, "    pub mod {module} {{");
        for f in &k.fields {
            let fn_name = rust_ident(&f.name);
            let slot = slot_ty(x, f);
            let key = x.field_key(&k.name, &f.name)?;
            let _ = writeln!(
                o,
                "        /// `{}.{}` — `{}`, card `{}`, emit `{}`.",
                k.name, f.name, f.raw_ty, f.card, f.emit
            );
            if f.derived {
                o.push_str(
                    "        /// Derived (62 §11.1): recomputed, never serialised, never an\n\
                     \x20       /// identity or similarity term.\n",
                );
            }
            doc_lines(&mut o, "        ", &f.doc);
            let _ = writeln!(
                o,
                "        pub fn {fn_name}<B: crate::bag::FieldBag + ?Sized>(bag: &B) -> Result<&{slot}, crate::bag::FieldError> {{"
            );
            let _ = writeln!(
                o,
                "            crate::bag::typed(bag, crate::bag::FieldKey({key}))"
            );
            o.push_str("        }\n");
        }
        o.push_str("    }\n");
    }

    // ---- the slot-type registry -------------------------------------------
    // The write-time half of the same fact the accessors read: a store that
    // erases its slots has to check an incoming value against the schema's
    // declared type, and hand-copying that table is how the two ends drift
    // (ADR-0008). Every registry key is covered, node and edge fields alike.
    let mut slots: Vec<(u32, String)> = Vec::new();
    for k in &x.kinds {
        for f in &k.fields {
            slots.push((x.field_key(&k.name, &f.name)?, slot_ty(x, f)));
        }
    }
    for e in x.edges.iter().chain(&x.derived_edges) {
        for f in &e.fields {
            slots.push((x.field_key(&e.name, &f.name)?, slot_ty(x, f)));
        }
    }
    slots.sort_by_key(|(k, _)| *k);
    o.push_str(
        "    /// The declared slot type for a wire key: its `TypeId` and the \
         exact type\n    /// path the read accessors use, for every entry in \
         the field-key registry,\n    /// node and edge fields alike. `None` \
         for a key this schema version does\n    /// not declare — a retired \
         key is never reused (62 §2.3).\n",
    );
    o.push_str(
        "    pub fn slot_type(key: crate::bag::FieldKey) -> Option<(core::any::TypeId, &'static str)> {\n        match key.0 {\n",
    );
    for (key, ty) in &slots {
        let _ = writeln!(
            o,
            "            {key} => Some((core::any::TypeId::of::<{ty}>(), \"{ty}\")),"
        );
    }
    o.push_str("            _ => None,\n        }\n    }\n");

    o.push_str("}\npub use body::*;\n");
    Ok(o)
}

/// The Rust type a field's slot holds, spelled from inside `fathom-ir`.
fn ty_str(x: &Extracted, ty: &FieldTy) -> String {
    match ty {
        FieldTy::Scalar(i) => {
            let p = x.scalars[*i]
                .impl_path
                .strip_prefix("fathom_ir::")
                .expect("validated at extract");
            format!("crate::{p}")
        }
        FieldTy::Primitive(p) => (*p).to_owned(),
        FieldTy::NodeId => "fathom_id::NodeId".to_owned(),
        FieldTy::Enum(i) => format!("crate::generated::ir_types::{}", x.enums[*i].rust_name),
        FieldTy::Inline(i) => format!(
            "crate::generated::ir_types::{}",
            x.inline_enums[*i].rust_name
        ),
        FieldTy::Set(i) => format!(
            "std::collections::BTreeSet<crate::generated::ir_types::{}>",
            x.enums[*i].rust_name
        ),
        FieldTy::Map(k, v) => format!(
            "std::collections::BTreeMap<{}, {}>",
            ty_str(x, k),
            ty_str(x, v)
        ),
    }
}

fn slot_ty(x: &Extracted, f: &FieldGen) -> String {
    let base = ty_str(x, &f.ty);
    if f.many() {
        format!("Vec<{base}>")
    } else {
        base
    }
}
