//! Golden vectors for every authority construction — **two independent
//! assemblies agreeing**, plus Wycheproof.
//!
//! `docs/PHASE-2-ADMIN-AND-AUDIT-DESIGN.md` §3.2, §3.3, §3.4 and §6.1.
//!
//! # Why this file exists, and what it is not
//!
//! The hex below was produced by
//! `crates/fathom-server/tests/vectors/gen_authority_vectors.py`, which lays
//! out every message from the text of §3 in plain Python, with its own `lp`,
//! `u32_le`, `u64_le`, SHA-256, HMAC-SHA-256, HKDF-Expand **and its own P-256
//! arithmetic**. **It does not call the Rust code, and this test does not call
//! the script.** The literals are literals. If the two agree, two people
//! reading the same specification laid the bytes out the same way; if either
//! is edited — a length prefix dropped, a field reordered, a label "tidied" —
//! they stop agreeing, and that is the whole of the control.
//!
//! `chain_vectors.rs` makes the same argument for the chain construction and
//! records what happens without it: the seal correction of 2026-09-12 was
//! pinned by nothing at all, and removing it left every test in this workspace
//! green.
//!
//! # What a failure here means
//!
//! Not "a test is broken". Either a signed construction changed — in which
//! case every signature ever made is invalidated and the change needs the
//! argument §3's own correction had to make — or it changed by accident, in
//! which case it is a silent break of every stored grant. Regenerating the
//! vectors to make this pass is the one repair that is never right.
//!
//! # The Wycheproof half
//!
//! `ecdsa_secp256r1_sha256_p1363_test.json` and
//! `ecdsa_secp256r1_sha256_test.json` from `C2SP/wycheproof`
//! (raw.githubusercontent.com, reachable and fetched 2026-09-12). The cases are
//! curated by the generator script, and **the expected outcome is this
//! product's, not Wycheproof's**: a Wycheproof-valid signature whose `s` is
//! high is refused here, because §3's correction admits exactly one encoding
//! per act. The script classifies `s` itself and derives the `(r, −s)` twin of
//! a valid case, because Wycheproof's own P1363 group carries no high-`s`
//! valid signature.

use fathom_server::authority::{
    self, Capability, GrantFacts, RowFacts, SignatureRefused, SoftwareKey,
};
use fathom_server::chain::{self, ChainRef};
use fathom_server::crypto::Key32;

// ---------------------------------------------------------------------------
// Generated by tests/vectors/gen_authority_vectors.py -- pasted, never read.
// ---------------------------------------------------------------------------
const PUBLIC_KEY: &str = "041e18532fd4754c02f3041d9c75ceb33b83ffd81ac7ce4fe882ccb1c98bc5896ea46c311c4e2ff40dd96a3653e6e454\
     45d32dfe486eced75c7a90c6a18881c0a3";
const KEY_FINGERPRINT: &str = "bb696e05eadbe40309d13723938eebc04ce20951cddc229b20053e6356d944c6";
const GRANT_BYTES: &str = "0f000000666174686f6d2f6772616e742f76311a00000030314a515a3030303030303030303030303030303030303041\
     412000000041414141414141414141414141414141414141414141414141414141414141411a00000030314a515a3030\
     303030303030303030303030303030303042421a00000030314a515a3030303030303030303030303030303030303043\
     432000000042424242424242424242424242424242424242424242424242424242424242420700000073746577617264\
     1a00000030314a515a303030303030303030303030303030303030304444200000004343434343434343434343434343\
     4343434343434343434343434343434343430078e76800000000803bb16a0000000007000000";
const SECOND_BYTES: &str = "16000000666174686f6d2f6772616e742f7365636f6e642f76312000000080f7ad8f2ae378e2bb98b1618572d9ca7020\
     6abbf0b227052f13898c0cae90bd20000000434343434343434343434343434343434343434343434343434343434343\
     4343";
const REVOKE_BYTES: &str = "16000000666174686f6d2f6772616e742f7265766f6b652f76311a00000030314a515a30303030303030303030303030\
     30303030303041411a00000030314a515a3030303030303030303030303030303030303045452000000080f7ad8f2ae3\
     78e2bb98b1618572d9ca70206abbf0b227052f13898c0cae90bd800e806900000000";
const SUSPEND_BYTES: &str = "17000000666174686f6d2f6772616e742f73757370656e642f76311a00000030314a515a303030303030303030303030\
     3030303030303041411a00000030314a515a3030303030303030303030303030303030303045452000000080f7ad8f2a\
     e378e2bb98b1618572d9ca70206abbf0b227052f13898c0cae90bd800e806900000000";
const UNSUSPEND_BYTES: &str = "19000000666174686f6d2f6772616e742f756e73757370656e642f76311a00000030314a515a30303030303030303030\
     30303030303030303041411a00000030314a515a3030303030303030303030303030303030303045452000000080f7ad\
     8f2ae378e2bb98b1618572d9ca70206abbf0b227052f13898c0cae90bd800e806900000000";
const SUCCESSION_BYTES: &str = "18000000666174686f6d2f6b65792f73756363657373696f6e2f76311a00000030314a515a3030303030303030303030\
     303030303030303046462000000044444444444444444444444444444444444444444444444444444444444444442000\
     00004545454545454545454545454545454545454545454545454545454545454545800e806900000000";
const ORG_CHAIN_KEY: &str = "c4c7db8438214073587a04221272de2e2fc34018a2ddea5660e2b7e3173334ed";
const K_ROW: &str = "6d8a379427f0c8303dbbbebc354f2d230d9e113d5b240045641a90c6107c5faa";
const K_SEAL: &str = "a9e1e0824b7e0e5143cc26230ef95076d88623d32e87ab0c2fd10686731a124d";
const ROW_SEAL: &str = "1813724da54cb668cbac06be321526d1bf3127128af3e937f572fe46661db9fe";
const LIVE_DIGEST: &str = "512314b84fb2b6473c95446d975ab522456cedb29a57db4be89840040d05150f";
const HEAD_SEAL: &str = "bf87009cbfd88c6aee8468f99dd35c3ec0d38bf5855ea61b94cb880b1c102737";
const SIGNATURE: &str = "1ed49eab8aa694e63551a54fa72c6be4b0e89181b39b1fe0eb8b49ab320bc5a06df3b0c915318c899188879b0e69b5cc\
     4122df16f510afcd1b5d22409de4794f";
const ORGANISATION_ID: &str = "3YW3CZP5ZNXSVFCBWPGQ7DCP7P";

/// Wycheproof, curated by the generator: `(public key, message, signature,
/// this product's outcome)`. Each row's outcome is THIS PRODUCT's, which is
/// not always Wycheproof's verdict — see the module doc.
const WYCHEPROOF: &[(&str, &str, &str, &str)] = &[
    // tcId 1: signature malleability
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "2ba3a8be6b94d5ec80a6d9d1190a436effe50d85a1eee859b8cc6af9bd5c2e184cd60b855d442f5b3c7b11eb6c4e0ae7525fe710fab9aa7c77a67f79e6fadd76", "Ok"),
    // tcId 2: replaced r by r + n
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "012ba3a8bd6b94d5ed80a6d9d1190a436ebccc0833490686deac8635bcb9bf536900b329f479a2bbd0a5c384ee1493b1f5186a87139cac5df4087c134b49156847db", "WrongLength"),
    // tcId 3: replaced r by r + 256 * n
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "01002ba3a7be6b94d6ec80a6d9d1190a432be6dfbb2cb98d6d4d72972df620817f180000b329f479a2bbd0a5c384ee1493b1f5186a87139cac5df4087c134b49156847db", "WrongLength"),
    // tcId 4: replaced r by n - r
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "d45c5740946b2a147f59262ee6f5bc90bd01ed280528b62b3aed5fc93f06f739b329f479a2bbd0a5c384ee1493b1f5186a87139cac5df4087c134b49156847db", "HighS"),
    // tcId 11: Signature with special case values r=0 and s=0
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "Malformed"),
    // tcId 12: Signature with special case values r=0 and s=1
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001", "Malformed"),
    // tcId 60: Edge case for Shamir multiplication
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "3639383139", "64a1aab5000d0e804f3e2fc02bdee9be8ff312334e2ba16d11547c97711c898e6af015971cc30be6d1a206d4e013e0997772a2f91d73286ffd683b9bb2cf4f1b", "Ok"),
    // tcId 61: special case hash
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "343236343739373234", "16aea964a2f6506d6f78c81c91fc7e8bded7d397738448de1e19a0ec580bf266252cd762130c6667cfe8b7bc47d27d78391e8e80c578d1cd38c3ff033be928e9", "Ok"),
    // tcId 1: the (r, -s) twin of the case above, derived here: valid ECDSA, refused
    ("042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e", "313233343030", "2ba3a8be6b94d5ec80a6d9d1190a436effe50d85a1eee859b8cc6af9bd5c2e18b329f479a2bbd0a5c384ee1493b1f5186a87139cac5df4087c134b49156847db", "HighS"),
    // tcId 1: DER encoding of a valid signature
    ("0404aaec73635726f213fb8a9e64da3b8632e41495a944d0045b522eba7240fad587d9315798aaa3a5ba01775787ced05eaaf7b4e09fc81d6d1aa546e8365d525d", "", "3045022100b292a619339f6e567a305c951c0dcbcc42d16e47f219f9e98e76e09d8770b34a02200177e60492c5a8242f76f07bfe3661bde59ec2a17ce5bd2dab2abebdf89a62e2", "WrongLength"),
];

// ---------------------------------------------------------------------------
// The same fixed inputs the script uses.
// ---------------------------------------------------------------------------

const ORGANISATION: &str = "01JQZ0000000000000000000AA";
const SCOPE: &str = "01JQZ0000000000000000000BB";
const SUBJECT: &str = "01JQZ0000000000000000000CC";
const GRANTER: &str = "01JQZ0000000000000000000DD";
const GRANT_ID: &str = "01JQZ0000000000000000000EE";
const ACCOUNT: &str = "01JQZ0000000000000000000FF";

const ROOT_PUBKEY_FPR: [u8; 32] = [0x41; 32];
const SUBJECT_KEY_FPR: [u8; 32] = [0x42; 32];
const GRANTER_KEY_FPR: [u8; 32] = [0x43; 32];
const OLD_KEY_FPR: [u8; 32] = [0x44; 32];
const NEW_KEY_FPR: [u8; 32] = [0x45; 32];

const EFFECTIVE_FROM: i64 = 1_760_000_000;
const EXPIRES_AT: i64 = 1_790_000_000;
const AUTH_EPOCH: i32 = 7;
const AT_UNIX: i64 = 1_770_000_000;
const ID_SALT: [u8; 16] = [0x5A; 16];

const ROW_CHAIN_SEQ: i64 = 4;
const ROW_VERSION: i32 = 1;
const ROW_STATE: &[u8] = b"{\"capability\":\"steward\"}\n";
const HEAD_CHAIN_SEQ: i64 = 9;
const CHAIN_KEY_EPOCH: i32 = 1;

fn chain_master() -> Key32 {
    let mut bytes = [0u8; 32];
    for (i, b) in bytes.iter_mut().enumerate() {
        *b = i as u8;
    }
    Key32::from_bytes(bytes)
}

fn private_scalar() -> [u8; 32] {
    [0x07; 32]
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("hex"))
        .collect()
}

fn facts() -> GrantFacts<'static> {
    GrantFacts {
        organisation: ORGANISATION,
        root_pubkey_fpr: &ROOT_PUBKEY_FPR,
        scope: SCOPE,
        subject: SUBJECT,
        subject_key_fpr: &SUBJECT_KEY_FPR,
        capability: Capability::Steward,
        granter: Some(GRANTER),
        granter_key_fpr: &GRANTER_KEY_FPR,
        effective_from_unix: EFFECTIVE_FROM,
        expires_at_unix: EXPIRES_AT,
        auth_epoch: AUTH_EPOCH,
    }
}

// ---------------------------------------------------------------------------
// The messages
// ---------------------------------------------------------------------------

#[test]
fn grant_bytes_are_the_bytes_the_document_describes() {
    assert_eq!(hex(&authority::grant_bytes(&facts())), GRANT_BYTES);
}

#[test]
fn second_bytes_bind_the_grant_and_the_granters_key_and_nothing_else() {
    let grant = authority::grant_bytes(&facts());
    assert_eq!(
        hex(&authority::second_bytes(&grant, &GRANTER_KEY_FPR)),
        SECOND_BYTES
    );
}

#[test]
fn revoke_suspend_and_unsuspend_bytes_are_three_different_messages() {
    let grant = authority::grant_bytes(&facts());
    assert_eq!(
        hex(&authority::revoke_bytes(
            ORGANISATION,
            GRANT_ID,
            &grant,
            AT_UNIX
        )),
        REVOKE_BYTES
    );
    assert_eq!(
        hex(&authority::suspend_bytes(
            ORGANISATION,
            GRANT_ID,
            &grant,
            AT_UNIX
        )),
        SUSPEND_BYTES
    );
    assert_eq!(
        hex(&authority::unsuspend_bytes(
            ORGANISATION,
            GRANT_ID,
            &grant,
            AT_UNIX
        )),
        UNSUSPEND_BYTES
    );
}

#[test]
fn succession_bytes_name_both_fingerprints_in_order() {
    assert_eq!(
        hex(&authority::succession_bytes(
            ACCOUNT,
            &OLD_KEY_FPR,
            &NEW_KEY_FPR,
            AT_UNIX
        )),
        SUCCESSION_BYTES
    );
}

// ---------------------------------------------------------------------------
// The seals
// ---------------------------------------------------------------------------

#[test]
fn the_row_key_is_a_third_subkey_of_the_organisation_chain_key() {
    let chain_key = chain::chain_key(
        &chain_master(),
        ChainRef::Org {
            organisation: ORGANISATION,
        },
        CHAIN_KEY_EPOCH,
    );
    assert_eq!(hex(chain_key.expose()), ORG_CHAIN_KEY);
    assert_eq!(hex(authority::row_key(&chain_key).expose()), K_ROW);
    assert_eq!(
        hex(chain::Subkeys::derive(&chain_key).seal.expose()),
        K_SEAL
    );
}

#[test]
fn the_row_seal_is_the_seal_the_document_describes() {
    let chain_key = chain::chain_key(
        &chain_master(),
        ChainRef::Org {
            organisation: ORGANISATION,
        },
        CHAIN_KEY_EPOCH,
    );
    let seal = authority::row_seal(
        &authority::row_key(&chain_key),
        &RowFacts {
            table: "scope_grants",
            row_id: GRANT_ID,
            chain_seq: ROW_CHAIN_SEQ,
            row_version: ROW_VERSION,
            row_state: ROW_STATE,
        },
    );
    assert_eq!(hex(&seal), ROW_SEAL);
}

#[test]
fn the_live_digest_and_the_head_seal_are_the_ones_the_document_describes() {
    let chain_key = chain::chain_key(
        &chain_master(),
        ChainRef::Org {
            organisation: ORGANISATION,
        },
        CHAIN_KEY_EPOCH,
    );
    let row_key = authority::row_key(&chain_key);
    // Handed over deliberately UNSORTED, because §3.4 sorts and the code must
    // not depend on its caller having done so.
    let live = vec![
        ("01JQZ0000000000000000000GG".to_string(), [0x61u8; 32]),
        ("01JQZ0000000000000000000EE".to_string(), [0x62u8; 32]),
    ];
    let digest = authority::live_digest(&row_key, ORGANISATION, AUTH_EPOCH, &live);
    assert_eq!(hex(&digest), LIVE_DIGEST);

    let seal = authority::head_seal(
        &chain::Subkeys::derive(&chain_key).seal,
        ORGANISATION,
        AUTH_EPOCH,
        HEAD_CHAIN_SEQ,
        &digest,
    );
    assert_eq!(hex(&seal), HEAD_SEAL);
}

// ---------------------------------------------------------------------------
// Identities
// ---------------------------------------------------------------------------

#[test]
fn the_public_key_and_its_fingerprint_are_what_the_script_derived() {
    let key = SoftwareKey::from_bytes(&private_scalar()).expect("a valid scalar");
    assert_eq!(hex(&key.public_key()), PUBLIC_KEY);
    assert_eq!(hex(&key.fingerprint()), KEY_FINGERPRINT);
    assert_eq!(
        hex(&authority::key_fingerprint(&unhex(PUBLIC_KEY))),
        KEY_FINGERPRINT
    );
}

#[test]
fn the_organisation_id_is_derived_from_the_root_key_and_the_salt() {
    let key = SoftwareKey::from_bytes(&private_scalar()).expect("a valid scalar");
    assert_eq!(
        authority::derive_organisation_id(&key.public_key(), &ID_SALT),
        ORGANISATION_ID
    );
}

// ---------------------------------------------------------------------------
// ES256
// ---------------------------------------------------------------------------

#[test]
fn signing_is_deterministic_and_the_signature_is_the_pinned_one() {
    // RFC 6979: `ecdsa 0.17.0`'s `Signer` derives the ephemeral scalar from
    // the key and the message, so this is a fixed value — and the Python
    // script VERIFIES it with its own P-256 arithmetic over its own
    // `grant_bytes`, which is the independent half.
    let key = SoftwareKey::from_bytes(&private_scalar()).expect("a valid scalar");
    let signature = key.sign(&authority::grant_bytes(&facts()));
    assert_eq!(hex(&signature), SIGNATURE);
    assert_eq!(
        authority::verify_es256(
            &key.public_key(),
            &authority::grant_bytes(&facts()),
            &signature
        ),
        Ok(())
    );
}

#[test]
fn wycheproof_cases_get_this_products_answer_and_not_wycheproofs() {
    assert!(
        !WYCHEPROOF.is_empty(),
        "the Wycheproof table is empty, which would make this test pass by \
         checking nothing. Re-run tests/vectors/gen_authority_vectors.py where \
         raw.githubusercontent.com is reachable and paste its table back."
    );
    for (public, message, signature, expected) in WYCHEPROOF {
        let outcome = authority::verify_es256(&unhex(public), &unhex(message), &unhex(signature));
        let got = match outcome {
            Ok(()) => "Ok".to_string(),
            Err(SignatureRefused::HighS) => "HighS".to_string(),
            Err(SignatureRefused::WrongLength { .. }) => "WrongLength".to_string(),
            Err(SignatureRefused::Malformed) => "Malformed".to_string(),
            Err(SignatureRefused::DoesNotVerify) => "DoesNotVerify".to_string(),
            Err(SignatureRefused::PublicKeyMalformed) => "PublicKeyMalformed".to_string(),
        };
        assert_eq!(&got, expected, "signature {signature}");
    }
}
