//! Golden vectors for every chain construction — **two independent assemblies
//! agreeing.**
//!
//! `docs/PHASE-2-STORAGE-DESIGN.md` §11.2 and §12.2, and `0009`'s two extra
//! labels.
//!
//! # Why this file exists, and what it is not
//!
//! The hex below was produced by
//! `crates/fathom-server/tests/vectors/gen_chain_vectors.py`, which lays out
//! every message from the text of §11.2 and §12.2 in plain Python, with its own
//! `lp`, `u32_le`, `u64_le`, HMAC-SHA-256 and HKDF-Expand. **It does not call
//! the Rust code, and this test does not call the script.** The literals are
//! literals. If the two agree, two people reading the same specification laid
//! the bytes out the same way; if either is edited — a length prefix dropped, a
//! field reordered, a label "tidied" — they stop agreeing, and that is the
//! whole of the control.
//!
//! **A test that derived its expected value from `fathom_server::chain` would
//! pass for any construction whatsoever**, including one with
//! `LP(metadata_binding)` deleted from the seal. That is not hypothetical: the
//! seal correction of 2026-09-12 was pinned by nothing at all, and removing it
//! left every test in this workspace green.
//!
//! # What a failure here means
//!
//! Not "a test is broken". Either the construction changed, in which case every
//! seal ever written is invalidated and the change needs the argument §11.2's
//! own correction had to make, or the change was accidental, in which case it
//! is a silent break of every stored history. Regenerating the vectors to make
//! this pass is the one repair that is never right.

use fathom_server::chain::{
    self, ChainRef, EntryType, PlaintextFacts, SealFacts, StorageFacts, Subkeys,
};
use fathom_server::crypto::Key32;

// ---------------------------------------------------------------------------
// Generated by tests/vectors/gen_chain_vectors.py -- pasted, never read.
// ---------------------------------------------------------------------------

const DESIGN_CHAIN_KEY: &str = "9c2aacde851c001ff3b938b2a83bb30842d48e597c92b68845b71d9edb525e3c";
const SITE_CHAIN_KEY: &str = "824d677b0c4a9acd73407cdea0e9f795cd63b142cd15ef29589029015ade2d59";
const ORG_CHAIN_KEY: &str = "35605faa3be3d2d0e5c1426071231ea18fe8c9eb8f232a42f56c21071e757b4b";
const SITE_METADATA_KEY: &str = "2da1a2cd744522edf3a0c4d8d5057140eab9ed19caf1d4083b3e8c9fe95cb5ff";
const K_SEAL: &str = "3ad23c0aaea47139aa48b2450bf335b73de143e500b076ba30ad3da0b4c5da15";
const K_CONTENT: &str = "827d4662ab8f966ba62d5012ed0d1111ffc81d41017b63dc3b5347d8bfbbe7a3";
const PLAINTEXT_BINDING: &str = "2cadd6e96f789a9fc55301b9490b73c9feb230774094c181646bb7caafc92dcb";
const STORAGE_BINDING: &str = "0d255c692c21949cadfd6c9465b0d142f654be70f596667442d416f17ba61285";
const CONTENT_HASH: &str = "b5d98b135111f0aa4f59b7cba51c616789455e04965ce9bfb1355618001e18fd";
const METADATA_BINDING: &str = "18937c1e2250ad1931bc2c687a25be48788a5223ea0fe2385982ec05321f61af";
const ABSENT_CONTENT_BINDING: &str =
    "1dc672cb580a0dfca52158cfaa50411f2e0ef0c6987301719f97678fd24deecc";
const SEAL: &str = "994f3dd37c0a6be46b701154651e4d2b74dbb1502dfc9f588d795efeb05313ca";
const GENESIS_DESIGN: &str = "a2141957a67f3f58f491678bb747132f2cc5df4c22c6f9d1440cbbe353b7fd0d";
const GENESIS_SITE: &str = "d29dc950bdddd8ebfdb780a6c1bd4259f99624df5928a31335cfa3be81c35d8e";
const GENESIS_ORG: &str = "6152fe3560ba5378f28f6f167fe4bf372f80b16e687ea90185b2ecd017f7fdc2";
const METADATA_AAD_ORG: &str = "1d000000666174686f6d2f636861696e2f6d657461646174612f616561642f7631\
030000006f72671a00000030314a515a303030303030303030303030303030303030304141\
040000000000000009000000";
const METADATA_AAD_SITE: &str = "1d000000666174686f6d2f636861696e2f6d657461646174612f616561642f76\
3104000000736974651a00000030314a515a30303030303030303030303030303030303030\
4343040000000000000007000000";
const DATA_KEY_ID: &str = "ed9d33deb35aea9b";

// ---------------------------------------------------------------------------
// The same fixed inputs the script uses. Chosen so no two are equal and none is
// all-zero: a vector over zeros agrees with a construction that dropped the
// field.
// ---------------------------------------------------------------------------

fn chain_master() -> Key32 {
    let mut bytes = [0u8; 32];
    for (i, b) in bytes.iter_mut().enumerate() {
        *b = i as u8;
    }
    Key32::from_bytes(bytes)
}

fn data_key() -> Key32 {
    Key32::from_bytes([0x11; 32])
}

const TENANT: &str = "01JQZ0000000000000000000AA";
const DESIGN: &str = "01JQZ0000000000000000000BB";
const DEPLOYMENT: &str = "01JQZ0000000000000000000CC";

const CHAIN_KEY_EPOCH: i32 = 7;
const SEQ: i64 = 4;
const DESIGN_VERSION: i64 = 3;
const PAYLOAD_SCHEMA_VERSION: i32 = 2;
const PAYLOAD: &[u8] = b"the estate";

const KEY_EPOCH: i32 = 5;
const WRAP_VERSION: i32 = 1;
const AEAD_ALG_ID: i16 = 1;
const CIPHERTEXT: &[u8] = b"ciphertext-including-tag";

const METADATA_CANONICAL: &[u8] =
    br#"{"actor":"01JQZ0000000000000000000AA","entry_type":"update"}"#;
const METADATA_STORED: &[u8] = b"the-aead-blob-as-stored";
const METADATA_KEY_EPOCH: i32 = 9;

fn nonce() -> [u8; 12] {
    let mut out = [0u8; 12];
    for (i, b) in out.iter_mut().enumerate() {
        *b = 0x20 + i as u8;
    }
    out
}

fn prev_seal() -> [u8; 32] {
    [0x33; 32]
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

const DESIGN_CHAIN: ChainRef<'static> = ChainRef::Design {
    organisation: TENANT,
    design: DESIGN,
};

// ---------------------------------------------------------------------------
// The vectors
// ---------------------------------------------------------------------------

#[test]
fn the_three_chain_key_derivations_and_the_site_metadata_key() {
    // §12.2's table, three of its rows plus `0009`'s. Each is length-prefixed
    // and domain-separated, which is what stops a run of entries lifted from
    // one chain verifying at another -- and what stops tenant `ab` + design
    // `c` deriving the same key as tenant `a` + design `bc`.
    let master = chain_master();
    assert_eq!(
        hex(chain::chain_key(&master, DESIGN_CHAIN, CHAIN_KEY_EPOCH).expose()),
        DESIGN_CHAIN_KEY,
        "the per-design chain key -- §12.2. This one may NEVER change: every seal already \
         written verifies under it."
    );
    assert_eq!(
        hex(chain::chain_key(
            &master,
            ChainRef::Site {
                deployment: DEPLOYMENT
            },
            CHAIN_KEY_EPOCH
        )
        .expose()),
        SITE_CHAIN_KEY,
    );
    assert_eq!(
        hex(chain::chain_key(
            &master,
            ChainRef::Org {
                organisation: TENANT
            },
            CHAIN_KEY_EPOCH
        )
        .expose()),
        ORG_CHAIN_KEY,
    );
    assert_eq!(
        hex(chain::site_metadata_key(&master, DEPLOYMENT, CHAIN_KEY_EPOCH).expose()),
        SITE_METADATA_KEY,
    );

    // And the three are different keys, which is the property the labels buy.
    assert_ne!(DESIGN_CHAIN_KEY, SITE_CHAIN_KEY);
    assert_ne!(SITE_CHAIN_KEY, ORG_CHAIN_KEY);
    assert_ne!(SITE_CHAIN_KEY, SITE_METADATA_KEY);
}

#[test]
fn the_two_subkeys() {
    // §12.2 renamed these labels so that the HKDF `info` and the in-MAC domain
    // tag are not the same literal. Pinned here because the failure mode of
    // "tidying" one of them is silent.
    let subkeys = Subkeys::derive(&chain::chain_key(
        &chain_master(),
        DESIGN_CHAIN,
        CHAIN_KEY_EPOCH,
    ));
    assert_eq!(hex(subkeys.seal.expose()), K_SEAL);
    assert_eq!(hex(subkeys.content.expose()), K_CONTENT);
}

#[test]
fn the_bindings_and_the_content_hash() {
    let subkeys = Subkeys::derive(&chain::chain_key(
        &chain_master(),
        DESIGN_CHAIN,
        CHAIN_KEY_EPOCH,
    ));

    // The data key's non-secret id, which is what enters `storage_binding` --
    // not the key.
    assert_eq!(hex(data_key().id().as_bytes()), DATA_KEY_ID);

    let plaintext = chain::plaintext_binding(
        &subkeys.content,
        &PlaintextFacts {
            tenant: TENANT,
            design: DESIGN,
            design_version: DESIGN_VERSION,
            payload_schema_version: PAYLOAD_SCHEMA_VERSION,
            payload: PAYLOAD,
        },
    );
    assert_eq!(hex(&plaintext), PLAINTEXT_BINDING);

    let storage = chain::storage_binding(
        &subkeys.content,
        &StorageFacts {
            key_id: data_key().id(),
            key_epoch: KEY_EPOCH,
            wrap_version: WRAP_VERSION,
            aead_alg_id: AEAD_ALG_ID,
            nonce: &nonce(),
            ciphertext: CIPHERTEXT,
        },
    );
    assert_eq!(hex(&storage), STORAGE_BINDING);

    let content_hash = chain::content_hash(&subkeys.content, &plaintext, &storage);
    assert_eq!(hex(&content_hash), CONTENT_HASH);

    assert_eq!(
        hex(&chain::metadata_binding(
            &subkeys.content,
            METADATA_CANONICAL
        )),
        METADATA_BINDING,
    );
    assert_eq!(
        hex(&chain::absent_content_binding(&subkeys.content)),
        ABSENT_CONTENT_BINDING,
    );
}

#[test]
fn the_seal_covers_the_metadata_as_stored_and_the_binding_of_its_plaintext() {
    // **The construction that was pinned by nothing.** `metadata_stored` and
    // the value `metadata_binding` covers are DIFFERENT bytes in this vector,
    // deliberately: a vector that used one value for both would agree with a
    // construction that had confused them, and one that omitted either would
    // agree with a seal that had dropped it.
    let subkeys = Subkeys::derive(&chain::chain_key(
        &chain_master(),
        DESIGN_CHAIN,
        CHAIN_KEY_EPOCH,
    ));
    let metadata_binding = chain::metadata_binding(&subkeys.content, METADATA_CANONICAL);
    let content_hash = {
        let mut bytes = [0u8; 32];
        for (i, b) in bytes.iter_mut().enumerate() {
            // The vector's `content_hash`, parsed back from its own hex so
            // this test does not depend on the binding test above passing.
            *b = u8::from_str_radix(&CONTENT_HASH[i * 2..i * 2 + 2], 16).unwrap();
        }
        bytes
    };

    let facts = SealFacts {
        chain_key_epoch: CHAIN_KEY_EPOCH,
        seq: SEQ,
        chain: DESIGN_CHAIN,
        prev_seal: &prev_seal(),
        content_hash: &content_hash,
        entry_type: EntryType::Update,
        metadata_stored: METADATA_STORED,
        metadata_binding: &metadata_binding,
    };
    assert_eq!(
        hex(&chain::seal(&subkeys.seal, &facts)),
        SEAL,
        "the seal input is §11.2's as corrected on 2026-09-12: \
         LP(tag) || u32(epoch) || u64(seq) || LP(id1) || LP(id2) || LP(prev_seal) || \
         LP(content_hash) || LP(entry_type) || LP(metadata_stored) || LP(metadata_binding)"
    );

    // And the verifier's constant-time path agrees with the value.
    let mut tag = [0u8; 32];
    for (i, b) in tag.iter_mut().enumerate() {
        *b = u8::from_str_radix(&SEAL[i * 2..i * 2 + 2], 16).unwrap();
    }
    assert!(chain::seal_verifies(&subkeys.seal, &facts, &tag));
}

#[test]
fn genesis_at_all_three_levels() {
    // §11.2's genesis, with the two deviations `chain::genesis` records: the
    // outer `LP` is how the value enters the MAC rather than part of it, and
    // the inner concatenation is length-prefixed.
    assert_eq!(hex(&chain::genesis(DESIGN_CHAIN)), GENESIS_DESIGN);
    assert_eq!(
        hex(&chain::genesis(ChainRef::Site {
            deployment: DEPLOYMENT
        })),
        GENESIS_SITE,
    );
    assert_eq!(
        hex(&chain::genesis(ChainRef::Org {
            organisation: TENANT
        })),
        GENESIS_ORG,
    );
}

#[test]
fn the_metadata_associated_data() {
    // `0009`'s label, and the reason a metadata blob cannot be moved to
    // another `seq`: the associated data names the row. The whole byte string
    // is pinned, not a digest of it, because it is short and because its shape
    // is the thing that matters.
    assert_eq!(
        hex(&chain::metadata_aad(
            ChainRef::Org {
                organisation: TENANT
            },
            SEQ,
            METADATA_KEY_EPOCH
        )),
        METADATA_AAD_ORG,
        "on an organisation entry the epoch is `metadata_key_epoch`, which names a row in \
         org_content_keys"
    );
    assert_eq!(
        hex(&chain::metadata_aad(
            ChainRef::Site {
                deployment: DEPLOYMENT
            },
            SEQ,
            CHAIN_KEY_EPOCH
        )),
        METADATA_AAD_SITE,
        "on a site entry it is `chain_key_epoch`, which is already on the row"
    );
}
