//! Golden vectors for the session layer: the hex `gen_session_vectors.py`
//! printed, recomputed here through `fathom_server::sessions`.
//!
//! **THE POINT IS TWO INDEPENDENT ASSEMBLIES AGREEING.**
//!
//! `tests/vectors/gen_session_vectors.py` builds every message below in plain
//! Python, from the text of `docs/PHASE-2-ADMIN-AND-AUDIT-DESIGN.md` §4.2 and
//! §4.3 — its own length prefixes, its own SHA-256, HMAC and HKDF, its own
//! canonical-JSON emitter and its own P-256 arithmetic. The constants here are
//! that script's output, pasted. Nothing in this file reads the script and
//! nothing in the script reads this file: if a length prefix is dropped, a
//! field reordered, a label tidied or the nonce quietly taken back out of
//! `request_bytes`, the two stop agreeing.
//!
//! A test that called the Rust code to produce its own expected value would
//! pass for any construction whatsoever, which is why none of these does.
//!
//! No database, no keys on disk, no network: every value is a pure function of
//! the constants at the top of the generator.

use fathom_server::authority::{self, SoftwareKey};
use fathom_server::chain::{self, ChainRef};
use fathom_server::crypto::Key32;
use fathom_server::sessions::{self, Assurance, PrincipalKind, SessionFacts};

// Generated by tests/vectors/gen_session_vectors.py -- paste, do not read.
const SESSION_PUBKEY: &str = "04462dba1ae4fc1a968b4dacf20cdd6dbe1fae34aa971514a63d3405c3d1cfd383b58bbb08c13383428c5853c71c4c85\
     1e134b056821e468fe0a977abf4313dde1";
const SESSION_CHALLENGE: &str = "316ad324a4f78a30c030b33885f7d05a43f242a3488553c468f93bf25578a984";
const BODY_DIGEST: &str = "30c5adaddc10b5c5a4e5753b214eb66c9c42dfdf44468c31bc70a6b666b1752d";
const REQUEST_BYTES: &str = "15000000666174686f6d2f73657373696f6e2f7265712f76311a00000030314a515a3030303030303030303030303030\
     30303030305353030000004745543b0000002f6f7267616e69736174696f6e732f30314a515a30303030303030303030\
     30303030303030303041412f6361706162696c6974793f61743d6e6f772000000030c5adaddc10b5c5a4e5753b214eb6\
     6c9c42dfdf44468c31bc70a6b666b1752d20000000323232323232323232323232323232323232323232323232323232\
     32323232327bc02cc8990100000900000000000000";
const TOKEN_HASH: &str = "f2f0e8631d980545ecc3873194afc5c919c9c76d13d41a4d9c3b7d380c02c659";
const EVIDENCE_DIGEST: &str = "b684337d3349dc75a11a942da71206cb9966932e796e1b0d85b40c2f177ac08e";
const SITE_CHAIN_KEY: &str = "dfb1f6e8e4a8f2681d40d8a1070217c28f32a77e31826aebbd8d27ab4cf87c89";
const K_ROW_SITE: &str = "f70afbf5d78612c1d99cbb037230d0904103f5661ceb004c2df5e0a4587f25ae";
const ROW_MAC: &str = "253859015ed20330baa1a5b53ce37b863bd3b3d5e4d7be5bbc74d9c280a1b259";
const SIGNATURE: &str = "f7287814e9e2082c43eed17e320b25e0f016c610aacfc187c5240cf1c7e8774b2f910812429571d9122bc2c1930fc96c\
     843ebc1ab854444ba884b3f7702215df";

// The generator's fixed inputs, restated here because a vector is a claim
// about a message over KNOWN inputs. No two are equal and none is all-zero: a
// vector over zeros agrees with a construction that dropped the field.
const CHAIN_MASTER: [u8; 32] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31,
];
const CHAIN_KEY_EPOCH: i32 = 1;
const DEPLOYMENT: &str = "01JQZ0000000000000000000DD";
const SESSION_ID: &str = "01JQZ0000000000000000000SS";
const PRINCIPAL_ID: &str = "01JQZ0000000000000000000AA";
const EVIDENCE_KEY_ID: &str = "01JQZ0000000000000000000KK";
const SERVER_NONCE: [u8; 32] = [0x31; 32];
const REQUEST_NONCE: [u8; 32] = [0x32; 32];
const TOKEN: [u8; 32] = [0x33; 32];
const EVIDENCE_SIG: [u8; 64] = [0x34; 64];
const SESSION_SCALAR: [u8; 32] = [0x21; 32];
const METHOD: &str = "GET";
const PATH: &str = "/organisations/01JQZ0000000000000000000AA/capability?at=now";
const BODY: &[u8] = b"the body this request actually carried";
const UNIX_MS: i64 = 1_760_000_000_123;
const REQUEST_COUNTER: i64 = 9;
const ISSUED_AT: i64 = 1_760_000_000;
const EXPIRES_AT: i64 = 1_760_043_200;
const CHAIN_SEQ: i64 = 12;
const ROW_VERSION: i32 = 1;

fn unhex(text: &str) -> Vec<u8> {
    let text: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    (0..text.len() / 2)
        .map(|i| u8::from_str_radix(&text[i * 2..i * 2 + 2], 16).expect("hex"))
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn session_key() -> SoftwareKey {
    SoftwareKey::from_bytes(&SESSION_SCALAR).expect("a valid scalar")
}

#[test]
fn the_fixed_session_key_is_the_one_the_generator_used() {
    assert_eq!(
        hex(&session_key().public_key()),
        unhex(SESSION_PUBKEY)
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    );
}

#[test]
fn the_session_challenge_matches_the_document() {
    let challenge =
        sessions::session_challenge(&session_key().public_key(), &SERVER_NONCE, DEPLOYMENT);
    assert_eq!(hex(&challenge), SESSION_CHALLENGE);
}

#[test]
fn the_body_digest_matches_the_document() {
    assert_eq!(hex(&sessions::body_digest(BODY)), BODY_DIGEST);
}

#[test]
fn the_request_message_matches_the_document() {
    let message = sessions::request_bytes(
        SESSION_ID,
        METHOD,
        PATH,
        &sessions::body_digest(BODY),
        &REQUEST_NONCE,
        UNIX_MS,
        REQUEST_COUNTER,
    );
    assert_eq!(
        hex(&message),
        hex(&unhex(REQUEST_BYTES)),
        "the per-request message is the one thing every protected route in this server rests on, \
         and the nonce inside it is this build's own addition to §4.2's layout"
    );
}

#[test]
fn the_signature_over_the_request_message_is_the_one_the_generator_verified() {
    // The generator cannot PRODUCE this signature -- RFC 6979's nonce
    // derivation is the signer's -- so it verifies it instead, with its own
    // P-256 arithmetic, over the message it assembled itself. That is the
    // stronger check of the two: a wrong `request_bytes` on either side makes
    // the verification fail.
    let signature = session_key().sign(&unhex(REQUEST_BYTES));
    assert_eq!(hex(&signature), SIGNATURE);
    assert_eq!(
        authority::verify_es256(
            &session_key().public_key(),
            &unhex(REQUEST_BYTES),
            &unhex(SIGNATURE)
        ),
        Ok(())
    );
}

#[test]
fn the_token_hash_matches_the_document() {
    assert_eq!(hex(&sessions::token_hash(&TOKEN)), TOKEN_HASH);
}

#[test]
fn the_evidence_digest_matches_the_document() {
    let challenge =
        sessions::session_challenge(&session_key().public_key(), &SERVER_NONCE, DEPLOYMENT);
    assert_eq!(
        hex(&sessions::evidence_digest(&challenge, &EVIDENCE_SIG)),
        EVIDENCE_DIGEST
    );
}

#[test]
fn the_site_scoped_row_key_matches_the_document() {
    let site = chain::chain_key(
        &Key32::from_bytes(CHAIN_MASTER),
        ChainRef::Site {
            deployment: DEPLOYMENT,
        },
        CHAIN_KEY_EPOCH,
    );
    assert_eq!(hex(site.expose()), SITE_CHAIN_KEY);
    assert_eq!(hex(authority::row_key(&site).expose()), K_ROW_SITE);
}

#[test]
fn the_session_row_mac_matches_the_document() {
    let key = Key32::from_bytes(
        unhex(K_ROW_SITE)
            .try_into()
            .expect("the row key is 32 bytes"),
    );
    let challenge =
        sessions::session_challenge(&session_key().public_key(), &SERVER_NONCE, DEPLOYMENT);
    let digest = sessions::evidence_digest(&challenge, &EVIDENCE_SIG);
    let pubkey = session_key().public_key();
    let token_hash = sessions::token_hash(&TOKEN);
    let mac = sessions::session_row_mac(
        &key,
        &SessionFacts {
            id: SESSION_ID,
            principal_id: PRINCIPAL_ID,
            principal_kind: PrincipalKind::Steward,
            token_hash: &token_hash,
            session_pubkey: &pubkey,
            bound_nonce: &SERVER_NONCE,
            evidence_key_id: Some(EVIDENCE_KEY_ID),
            evidence_sig: Some(&EVIDENCE_SIG),
            assertion_digest: Some(&digest),
            assurance: Assurance::A1,
            chain_seq: CHAIN_SEQ,
            row_version: ROW_VERSION,
            issued_at_unix: ISSUED_AT,
            expires_at_unix: EXPIRES_AT,
        },
    );
    assert_eq!(
        hex(&mac),
        ROW_MAC,
        "§4.3's second fence: a tier-2 attacker cannot mint a session row, because this key is \
         not in PostgreSQL. The canonical row state it is taken over is assembled twice, once \
         here and once in Python"
    );
}

#[test]
fn every_field_of_the_row_state_is_inside_the_mac() {
    // The vector proves one value. This proves the fields are load-bearing:
    // change any one of them and the MAC moves. A construction that dropped a
    // field would still match the vector if the vector were the only test.
    let key = Key32::from_bytes([9u8; 32]);
    let pubkey = session_key().public_key();
    let token_hash = sessions::token_hash(&TOKEN);
    let digest = [7u8; 32];
    let facts = || SessionFacts {
        id: SESSION_ID,
        principal_id: PRINCIPAL_ID,
        principal_kind: PrincipalKind::Steward,
        token_hash: &token_hash,
        session_pubkey: &pubkey,
        bound_nonce: &SERVER_NONCE,
        evidence_key_id: Some(EVIDENCE_KEY_ID),
        evidence_sig: Some(&EVIDENCE_SIG),
        assertion_digest: Some(&digest),
        assurance: Assurance::A1,
        chain_seq: CHAIN_SEQ,
        row_version: ROW_VERSION,
        issued_at_unix: ISSUED_AT,
        expires_at_unix: EXPIRES_AT,
    };
    let base = sessions::session_row_mac(&key, &facts());

    let other_token = [0x99u8; 32];
    let other_nonce = [0x98u8; 32];
    let other_digest = [0x97u8; 32];
    let variants: Vec<SessionFacts<'_>> = vec![
        SessionFacts {
            id: "01JQZ0000000000000000000ST",
            ..facts()
        },
        SessionFacts {
            principal_id: "01JQZ0000000000000000000AB",
            ..facts()
        },
        SessionFacts {
            principal_kind: PrincipalKind::Operator,
            ..facts()
        },
        SessionFacts {
            token_hash: &other_token,
            ..facts()
        },
        SessionFacts {
            bound_nonce: &other_nonce,
            ..facts()
        },
        SessionFacts {
            evidence_key_id: None,
            ..facts()
        },
        SessionFacts {
            assertion_digest: Some(&other_digest),
            ..facts()
        },
        SessionFacts {
            assurance: Assurance::A0,
            ..facts()
        },
        SessionFacts {
            chain_seq: CHAIN_SEQ + 1,
            ..facts()
        },
        SessionFacts {
            row_version: ROW_VERSION + 1,
            ..facts()
        },
        SessionFacts {
            issued_at_unix: ISSUED_AT + 1,
            ..facts()
        },
        SessionFacts {
            expires_at_unix: EXPIRES_AT + 1,
            ..facts()
        },
    ];
    for (n, variant) in variants.iter().enumerate() {
        assert_ne!(
            base,
            sessions::session_row_mac(&key, variant),
            "field {n} is not covered by the session row MAC"
        );
    }
}

#[test]
fn a_session_row_mac_is_not_an_authority_row_seal() {
    // `row_seal` length-prefixes the table name, so a session row lifted into
    // an authority table -- or the reverse -- does not verify where it lands.
    let key = Key32::from_bytes([5u8; 32]);
    let pubkey = session_key().public_key();
    let token_hash = sessions::token_hash(&TOKEN);
    let state = sessions::session_row_mac(
        &key,
        &SessionFacts {
            id: SESSION_ID,
            principal_id: PRINCIPAL_ID,
            principal_kind: PrincipalKind::Steward,
            token_hash: &token_hash,
            session_pubkey: &pubkey,
            bound_nonce: &SERVER_NONCE,
            evidence_key_id: None,
            evidence_sig: None,
            assertion_digest: None,
            assurance: Assurance::A0,
            chain_seq: CHAIN_SEQ,
            row_version: ROW_VERSION,
            issued_at_unix: ISSUED_AT,
            expires_at_unix: EXPIRES_AT,
        },
    );
    let elsewhere = authority::row_seal(
        &key,
        &authority::RowFacts {
            table: "scope_grants",
            row_id: SESSION_ID,
            chain_seq: CHAIN_SEQ,
            row_version: ROW_VERSION,
            row_state: b"{}\n",
        },
    );
    assert_ne!(state, elsewhere);
}

#[test]
fn the_label_list_is_the_one_the_generator_used() {
    // `PHASE-2-STORAGE-DESIGN.md` §12.2's table owns these names and wins over
    // the code. This asserts the two files at least agree on the set.
    let generator = include_str!("vectors/gen_session_vectors.py");
    for (label, _) in sessions::LABELS {
        assert!(
            generator.contains(label),
            "{label} is in sessions::LABELS and the generator does not know it, so one of the \
             two assemblies is not assembling it"
        );
    }
}
