//! 62 §17.2's determinism requirements, as tests — this file IS the CI
//! wiring for `schema.codegen.stale` and `schema.codegen.nondeterministic`
//! (fathom-schema-check lists both as checked here, not there).

use fathom_schemagen::{generate, GenError, ARTIFACT_PATHS};
use std::fs;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    // crates/fathom-schemagen -> crates -> repo root. A test-harness path,
    // never a generation input — the generator itself reads no environment.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crate lives two levels under the repo root")
        .to_path_buf()
}

fn schema_root() -> PathBuf {
    repo_root().join("schema")
}

/// schema.codegen.nondeterministic (62 §18.1): run twice, byte-compare.
#[test]
fn generator_is_byte_deterministic_across_runs() {
    let a = generate(&schema_root()).expect("shipped tree generates");
    let b = generate(&schema_root()).expect("shipped tree generates");
    assert_eq!(a.len(), b.len());
    for (x, y) in a.iter().zip(&b) {
        assert_eq!(x.repo_path, y.repo_path);
        assert!(
            x.bytes == y.bytes,
            "schema.codegen.nondeterministic: {} differs between two runs",
            x.repo_path
        );
    }
}

/// schema.codegen.stale (62 §18.1): regenerate and byte-compare against the
/// checked-in artifacts.
#[test]
fn checked_in_artifacts_are_current() {
    let artifacts = generate(&schema_root()).expect("shipped tree generates");
    assert_eq!(
        artifacts.iter().map(|a| a.repo_path).collect::<Vec<_>>(),
        ARTIFACT_PATHS.to_vec(),
        "the artifact set is fixed"
    );
    for a in &artifacts {
        let disk = fs::read(repo_root().join(a.repo_path)).unwrap_or_else(|e| {
            panic!(
                "schema.codegen.stale: {} unreadable ({e}) — run `cargo run -p fathom-schemagen`",
                a.repo_path
            )
        });
        assert!(
            disk == a.bytes,
            "schema.codegen.stale: {} differs from the generator's output — \
             run `cargo run -p fathom-schemagen`",
            a.repo_path
        );
    }
}

/// The generated directories hold exactly the artifact set — a stray or
/// hand-added file there would silently escape the stale check above.
#[test]
fn generated_dirs_hold_exactly_the_artifact_set() {
    let expect = [
        ("schema/generated", vec!["ir_types.ts", "schema.json"]),
        (
            "crates/fathom-ir/src/generated",
            vec!["accessors.rs", "ir_types.rs"],
        ),
        ("schema/migrations", vec!["manifest.toml"]),
    ];
    for (dir, want) in expect {
        let mut got: Vec<String> = fs::read_dir(repo_root().join(dir))
            .unwrap_or_else(|e| panic!("{dir}: {e}"))
            .map(|e| {
                e.expect("dir entry")
                    .file_name()
                    .to_string_lossy()
                    .into_owned()
            })
            .collect();
        got.sort();
        assert_eq!(got, want, "unexpected contents in {dir}");
    }
}

/// No output may carry an absolute path — the tree's location is not part
/// of its content (62 §17.2 requirement 1).
#[test]
fn outputs_carry_no_absolute_paths() {
    let root = repo_root()
        .canonicalize()
        .expect("repo root resolves")
        .to_string_lossy()
        .into_owned();
    for a in generate(&schema_root()).expect("shipped tree generates") {
        let text = String::from_utf8(a.bytes).expect("all outputs are UTF-8");
        assert!(
            !text.contains(&root),
            "{} embeds the repo root path",
            a.repo_path
        );
        assert!(
            !text.contains("/home/"),
            "{} embeds an absolute home path",
            a.repo_path
        );
    }
}

/// Every artifact opens with the generated-file header in its own comment
/// syntax; JSON, having no comments, opens with the `$generated` key (which
/// sorts first by construction).
#[test]
fn every_artifact_opens_with_the_generated_header() {
    for a in generate(&schema_root()).expect("shipped tree generates") {
        let text = String::from_utf8(a.bytes).expect("UTF-8");
        let ok = if a.repo_path.ends_with(".json") {
            text.starts_with("{\"$generated\":\"GENERATED by fathom-schemagen from schema/")
        } else if a.repo_path.ends_with(".toml") {
            text.starts_with("# GENERATED by fathom-schemagen from schema/")
        } else {
            text.starts_with("// GENERATED by fathom-schemagen from schema/")
        };
        assert!(ok, "{} lacks the generated header", a.repo_path);
    }
    // And no generation stamp anywhere: the header rule (62 §17.2) is "no
    // timestamp". An ISO-dated stamp would carry the current decade.
    let manifest = fs::read_to_string(repo_root().join("schema/migrations/manifest.toml")).unwrap();
    assert!(!manifest.contains("202"), "manifest smells of a timestamp");
}

/// The canonical-form contract for schema.json beyond the emitter's unit
/// tests: single line + trailing LF, no CR, valid UTF-8.
#[test]
fn schema_json_is_one_canonical_line() {
    let artifacts = generate(&schema_root()).expect("shipped tree generates");
    let json = artifacts
        .iter()
        .find(|a| a.repo_path.ends_with("schema.json"))
        .expect("schema.json in the set");
    let text = std::str::from_utf8(&json.bytes).expect("UTF-8");
    assert!(text.ends_with('\n'), "trailing newline required");
    let body = &text[..text.len() - 1];
    assert!(
        !body.contains('\n'),
        "no insignificant whitespace: one line"
    );
    assert!(!body.contains('\r'), "LF only");
}

/// `schema.json` carries every top-level block of `schema.yaml` — released
/// snapshots ARE this file, and the bump checker (62 §16.4) classifies
/// snapshot diffs against §16.2's table, whose rows include constraint
/// changes; an uncarried block (constraints/emission/matching/
/// naming_eligible were once omitted) is a class of change the checker can
/// never see.
#[test]
fn schema_json_carries_every_tree_block() {
    let tree_keys: Vec<String> = {
        let text = fs::read_to_string(schema_root().join("schema.yaml")).expect("schema.yaml");
        let node = fathom_schema::subset::parse(&text).expect("shipped tree parses");
        node.as_map()
            .expect("schema.yaml is a map")
            .iter()
            .map(|(k, _)| k.clone())
            .collect()
    };
    assert!(
        tree_keys.iter().any(|k| k == "constraints"),
        "the defect's block must be in the tree for this test to mean anything"
    );

    let artifacts = generate(&schema_root()).expect("shipped tree generates");
    let json = artifacts
        .iter()
        .find(|a| a.repo_path.ends_with("schema.json"))
        .expect("schema.json in the set");
    let top = top_level_keys(std::str::from_utf8(&json.bytes).expect("UTF-8"));
    for key in &tree_keys {
        assert!(
            top.contains(key),
            "schema.yaml block `{key}:` missing from schema.json's top level \
             — the bump checker (62 §16.4) would be blind to its changes"
        );
    }
}

/// Depth-1 object keys of a canonical (minified, string-escaped) JSON text.
fn top_level_keys(text: &str) -> Vec<String> {
    let mut keys = Vec::new();
    let mut depth = 0usize;
    let mut in_str = false;
    let mut escaped = false;
    let mut current = String::new();
    let mut key_position = false; // true right after `{` or `,` at depth 1
    for c in text.chars() {
        if in_str {
            if escaped {
                escaped = false;
                current.push(c);
            } else if c == '\\' {
                escaped = true;
            } else if c == '"' {
                in_str = false;
                if depth == 1 && key_position {
                    keys.push(std::mem::take(&mut current));
                }
                current.clear();
            } else {
                current.push(c);
            }
            continue;
        }
        match c {
            '"' => in_str = true,
            '{' | '[' => {
                depth += 1;
                key_position = c == '{';
            }
            '}' | ']' => depth -= 1,
            ',' => key_position = depth == 1,
            ':' => key_position = false,
            _ => {}
        }
    }
    keys
}

/// Gates first, then codegen: a tree with a failure-severity finding must
/// refuse to generate (never generate from a broken tree).
#[test]
fn generator_refuses_a_tree_with_gate_failures() {
    let dst = Path::new(env!("CARGO_TARGET_TMPDIR")).join("broken-tree");
    if dst.exists() {
        fs::remove_dir_all(&dst).expect("clean scratch");
    }
    copy_tree(&schema_root(), &dst);

    // An unknown top-level key is the cheapest failure-severity finding
    // (schema.order.toplevel).
    let schema_yaml = dst.join("schema.yaml");
    let mut text = fs::read_to_string(&schema_yaml).unwrap();
    text.push_str("\nzzz_not_a_declared_block: 1\n");
    fs::write(&schema_yaml, text).unwrap();

    match generate(&dst) {
        Err(GenError::Gates(findings)) => {
            assert!(
                findings.iter().any(|f| f.code == "schema.order.toplevel"),
                "expected schema.order.toplevel among the refusal's findings"
            );
        }
        Err(other) => panic!("expected a gate refusal, got: {other}"),
        Ok(_) => panic!("generated from a tree with failure-severity findings"),
    }
}

fn copy_tree(src: &Path, dst: &Path) {
    fs::create_dir_all(dst).expect("create scratch dir");
    for entry in fs::read_dir(src).expect("read schema tree") {
        let entry = entry.expect("dir entry");
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_tree(&from, &to);
        } else {
            fs::copy(&from, &to).expect("copy tree file");
        }
    }
}
